import { type TargetZone } from "@/components/FigmaUILocator";

export type StepType = "action" | "quiz";

export interface LocalizedText {
  ko: string;
  en: string;
}

export interface BaseStep {
  id: number;
  imageAlt: LocalizedText;
  targetZone?: TargetZone;
  shortcutKey?: string;
  troubleshootTip?: LocalizedText;
}

export interface ActionStep extends BaseStep {
  type: "action";
  instruction: LocalizedText;
  buttonText: LocalizedText;
}

export interface QuizStep extends BaseStep {
  type: "quiz";
  question: LocalizedText;
  options: LocalizedText[];
  correctIndex: number;
  successMessage: LocalizedText;
}

export type MissionStep = ActionStep | QuizStep;

export interface DayMission {
  day: number;
  title: LocalizedText;
  subtitle: LocalizedText;
  steps: MissionStep[];
}

export const missionContent: DayMission[] = [
  {
    day: 1,
    title: { ko: "첫 번째 접촉", en: "First Contact" },
    subtitle: { ko: "Figma 세계에 오신 것을 환영합니다", en: "Welcome to the Figma world" },
    steps: [
      {
        id: 1,
        type: "action",
        instruction: { ko: "figma.com에 접속하고 로그인하세요.", en: "Go to figma.com and log in." },
        buttonText: { ko: "로그인 완료!", en: "Logged in!" },
        imageAlt: { ko: "Figma 로그인 화면", en: "Figma login screen" },
        targetZone: "none",
        troubleshootTip: { ko: "Google 계정이나 이메일로 회원가입할 수 있어요. 이미 계정이 있다면 로그인하세요.", en: "You can sign up with Google or email. If you already have an account, just log in." },
      },
      {
        id: 2,
        type: "action",
        instruction: { ko: "오른쪽 상단의 'Design File' (파란 버튼)을 클릭하세요.", en: "Click 'Design File' (blue button) in the top right corner." },
        buttonText: { ko: "파일 생성 완료!", en: "File created!" },
        imageAlt: { ko: "Design File 버튼 위치", en: "Design File button location" },
        targetZone: "toolbar-top",
        troubleshootTip: { ko: "파란색 '+ Design file' 버튼이 보이지 않으면, 홈 화면으로 이동해보세요. 왼쪽 상단의 Figma 로고를 클릭하면 됩니다.", en: "If you don't see the blue '+ Design file' button, go to the home screen by clicking the Figma logo in the top left." },
      },
      {
        id: 3,
        type: "quiz",
        question: { ko: "화면을 보세요. 무한 캔버스의 배경색은 무슨 색인가요?", en: "Look at your screen. What color is the infinite canvas background?" },
        options: [
          { ko: "흰색", en: "White" },
          { ko: "연한 회색", en: "Light Gray" },
          { ko: "검은색", en: "Black" }
        ],
        correctIndex: 1,
        successMessage: { ko: "정답! 연한 회색이 Figma의 기본 캔버스 색상이에요.", en: "Correct! Light gray is Figma's default canvas color." },
        imageAlt: { ko: "Figma 캔버스 배경", en: "Figma canvas background" },
        targetZone: "canvas",
        troubleshootTip: { ko: "캔버스는 화면 중앙의 넓은 영역이에요. 프레임이나 도형이 아닌 배경 자체를 보세요.", en: "The canvas is the large area in the center. Look at the background itself, not frames or shapes." },
      },
      {
        id: 4,
        type: "action",
        instruction: { ko: "첫 번째 단축키를 외워볼까요? 키보드에서 'F'를 누르세요.", en: "Let's memorize your first shortcut. Press 'F' on your keyboard." },
        buttonText: { ko: "'F' 눌렀어요!", en: "Pressed 'F'!" },
        imageAlt: { ko: "키보드 F 키", en: "Keyboard F key" },
        targetZone: "toolbar-top",
        shortcutKey: "F",
        troubleshootTip: { ko: "텍스트 편집 모드에서는 단축키가 작동하지 않아요. 캔버스의 빈 공간을 한 번 클릭한 후 F를 눌러보세요.", en: "Shortcuts don't work in text editing mode. Click an empty area of the canvas first, then press F." },
      },
      {
        id: 5,
        type: "quiz",
        question: { ko: "마우스 커서가 어떻게 변했나요?", en: "How did your mouse cursor change?" },
        options: [
          { ko: "사라졌다", en: "It disappeared" },
          { ko: "십자가(+) 모양으로 변했다", en: "It turned into a crosshair (+)" },
          { ko: "손 모양으로 변했다", en: "It turned into a hand" }
        ],
        correctIndex: 1,
        successMessage: { ko: "맞아요! 십자가 커서는 '그리기 모드'라는 뜻이에요.", en: "Right! The crosshair cursor means you're in 'draw mode'." },
        imageAlt: { ko: "십자가 커서", en: "Crosshair cursor" },
        targetZone: "canvas",
        troubleshootTip: { ko: "커서 변화가 안 보이면 F를 다시 눌러보세요. 상단 툴바에서 Frame 도구가 선택되어 있는지 확인하세요.", en: "If you don't see the cursor change, press F again. Check if the Frame tool is selected in the top toolbar." },
      },
      {
        id: 6,
        type: "action",
        instruction: { ko: "좋아요! 이제 아무 곳이나 클릭하고 드래그해서 흰색 박스(프레임)를 그리세요.", en: "Great! Now click and drag anywhere to draw a white box (frame)." },
        buttonText: { ko: "프레임 완성!", en: "Frame done!" },
        imageAlt: { ko: "프레임 그리기", en: "Drawing a frame" },
        targetZone: "canvas",
        troubleshootTip: { ko: "클릭한 채로 드래그해야 해요. 클릭만 하면 프레임 옵션 패널이 나타납니다. 드래그하면서 원하는 크기로 그리세요.", en: "Hold click and drag. Just clicking shows the frame options panel. Drag to draw the size you want." },
      },
      {
        id: 7,
        type: "action",
        instruction: { ko: "왼쪽 패널(레이어)을 보세요. 'Frame 1'이 보이나요?", en: "Look at the left panel (Layers). Do you see 'Frame 1'?" },
        buttonText: { ko: "보여요!", en: "I see it!" },
        imageAlt: { ko: "레이어 패널에 Frame 1", en: "Frame 1 in Layers panel" },
        targetZone: "sidebar-left",
        troubleshootTip: { ko: "왼쪽 패널이 안 보이면 View > Panels > Layers를 클릭하거나, 왼쪽 가장자리를 드래그해서 패널을 열어보세요.", en: "If you don't see the left panel, click View > Panels > Layers, or drag from the left edge to open it." },
      },
      {
        id: 8,
        type: "action",
        instruction: { ko: "'R'을 눌러 사각형 도구를 선택하고, 프레임 '안에' 박스를 그리세요.", en: "Press 'R' for Rectangle tool and draw a box 'inside' the frame." },
        buttonText: { ko: "사각형 완성!", en: "Rectangle done!" },
        imageAlt: { ko: "사각형 그리기", en: "Drawing a rectangle" },
        targetZone: "canvas",
        shortcutKey: "R",
        troubleshootTip: { ko: "반드시 흰색 프레임 '안에' 그려야 해요. 프레임 밖에 그리면 레이어 패널에서 Frame 1의 자식으로 표시되지 않습니다.", en: "Make sure to draw 'inside' the white frame. If drawn outside, it won't show as a child of Frame 1 in the Layers panel." },
      },
      {
        id: 9,
        type: "quiz",
        question: { ko: "사각형의 색상을 바꾸려면 어느 패널을 사용해야 할까요?", en: "Which panel should you use to change the rectangle's color?" },
        options: [
          { ko: "왼쪽 패널", en: "Left Panel" },
          { ko: "오른쪽 패널", en: "Right Panel" },
          { ko: "상단 바", en: "Top Bar" }
        ],
        correctIndex: 1,
        successMessage: { ko: "정답! 오른쪽 패널에서 디자인 속성을 수정할 수 있어요.", en: "Correct! You can modify design properties in the right panel." },
        imageAlt: { ko: "오른쪽 디자인 패널", en: "Right design panel" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "오른쪽 패널이 안 보이면 사각형을 선택한 상태인지 확인하세요. 선택된 요소가 있어야 속성 패널이 표시됩니다.", en: "If you don't see the right panel, make sure the rectangle is selected. The properties panel shows only when an element is selected." },
      },
      {
        id: 10,
        type: "action",
        instruction: { ko: "오른쪽 패널에서 'Fill' 색상 사각형을 클릭하고 빨간색을 선택하세요.", en: "Click the 'Fill' color square in the right panel and choose red." },
        buttonText: { ko: "색상 변경 완료!", en: "Color changed!" },
        imageAlt: { ko: "Fill 색상 변경", en: "Changing Fill color" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "Fill 섹션에서 색상 사각형을 클릭하면 컬러 피커가 열려요. 빨간색 영역으로 드래그하거나 Hex 값에 FF0000을 입력하세요.", en: "Click the color square in Fill section to open the color picker. Drag to the red area or enter FF0000 in the Hex field." },
      },
    ],
  },
  {
    day: 2,
    title: { ko: "인터페이스 탐험", en: "Interface Exploration" },
    subtitle: { ko: "Figma의 핵심 도구들을 마스터하세요", en: "Master Figma's core tools" },
    steps: [
      {
        id: 1,
        type: "action",
        instruction: { ko: "키보드에서 'F'를 누르세요 (프레임 도구).", en: "Press 'F' on your keyboard (Frame tool)." },
        buttonText: { ko: "'F' 눌렀어요!", en: "Pressed 'F'!" },
        imageAlt: { ko: "F 키 - 프레임 도구", en: "F key - Frame tool" },
        targetZone: "toolbar-top",
        shortcutKey: "F",
        troubleshootTip: { ko: "캔버스 영역을 먼저 클릭해서 Figma에 포커스를 주세요. 다른 프로그램이 활성화되어 있으면 단축키가 작동하지 않아요.", en: "Click the canvas area first to focus Figma. Shortcuts won't work if another program is active." },
      },
      {
        id: 2,
        type: "action",
        instruction: { ko: "오른쪽 패널에서 'iPhone 14'를 선택하세요.", en: "Select 'iPhone 14' in the right panel." },
        buttonText: { ko: "iPhone 14 선택 완료!", en: "iPhone 14 selected!" },
        imageAlt: { ko: "iPhone 14 프리셋", en: "iPhone 14 preset" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "Frame 도구가 선택된 상태에서 오른쪽 패널 상단의 'Phone' 섹션을 찾으세요. iPhone 14가 목록에 있어요.", en: "With Frame tool selected, find the 'Phone' section at the top of the right panel. iPhone 14 is in the list." },
      },
      {
        id: 3,
        type: "quiz",
        question: { ko: "방금 만든 흰색 화면을 뭐라고 부를까요?", en: "What do we call the white screen you just created?" },
        options: [
          { ko: "레이어", en: "Layer" },
          { ko: "프레임", en: "Frame" },
          { ko: "캔버스", en: "Canvas" }
        ],
        correctIndex: 1,
        successMessage: { ko: "정답! 프레임은 Figma에서 화면이나 컨테이너를 의미해요.", en: "Correct! A frame in Figma represents a screen or container." },
        imageAlt: { ko: "프레임 설명", en: "Frame explanation" },
        targetZone: "canvas",
        troubleshootTip: { ko: "프레임은 Figma의 기본 단위예요. 웹 디자인의 div나 앱 디자인의 화면과 비슷한 개념입니다.", en: "Frames are the basic unit in Figma. They're similar to div in web design or screens in app design." },
      },
      {
        id: 4,
        type: "action",
        instruction: { ko: "'R'을 누르세요 (사각형 도구).", en: "Press 'R' (Rectangle tool)." },
        buttonText: { ko: "'R' 눌렀어요!", en: "Pressed 'R'!" },
        imageAlt: { ko: "R 키 - 사각형 도구", en: "R key - Rectangle tool" },
        targetZone: "toolbar-top",
        shortcutKey: "R",
        troubleshootTip: { ko: "R을 누르면 상단 툴바의 도형 메뉴에서 Rectangle이 선택됩니다. 커서가 십자가 모양으로 바뀌는지 확인하세요.", en: "Pressing R selects Rectangle in the shape menu. Check if the cursor turns into a crosshair." },
      },
      {
        id: 5,
        type: "action",
        instruction: { ko: "프레임 안에 상자를 그리세요.", en: "Draw a box inside the frame." },
        buttonText: { ko: "상자 완성!", en: "Box done!" },
        imageAlt: { ko: "사각형 그리기", en: "Drawing a rectangle" },
        targetZone: "canvas",
        troubleshootTip: { ko: "iPhone 14 프레임 경계 안에서 드래그하세요. 왼쪽 레이어 패널에서 Rectangle이 Frame의 하위 요소로 표시되는지 확인하세요.", en: "Drag inside the iPhone 14 frame boundary. Check if Rectangle shows as a child of Frame in the left Layers panel." },
      },
      {
        id: 6,
        type: "action",
        instruction: { ko: "'스페이스바'를 누른 채로 마우스를 드래그하세요 (Pan 이동).", en: "Hold 'Spacebar' and drag the mouse (Pan movement)." },
        buttonText: { ko: "캔버스 이동 완료!", en: "Canvas moved!" },
        imageAlt: { ko: "Pan 이동", en: "Pan movement" },
        targetZone: "canvas",
        shortcutKey: "Space",
        troubleshootTip: { ko: "스페이스바를 누르고 있는 동안 커서가 손 모양으로 바뀌어야 해요. 그 상태에서 마우스를 드래그하면 캔버스가 이동합니다.", en: "While holding spacebar, the cursor should turn into a hand. Drag the mouse in that state to move the canvas." },
      },
      {
        id: 7,
        type: "quiz",
        question: { ko: "확대/축소하려면 어떤 키를 누른 채로 스크롤해야 할까요?", en: "Which key should you hold while scrolling to zoom in/out?" },
        options: [
          { ko: "Shift", en: "Shift" },
          { ko: "Ctrl (또는 Cmd)", en: "Ctrl (or Cmd)" },
          { ko: "Alt", en: "Alt" }
        ],
        correctIndex: 1,
        successMessage: { ko: "맞아요! Ctrl/Cmd + 스크롤로 확대/축소할 수 있어요.", en: "Right! You can zoom with Ctrl/Cmd + scroll." },
        imageAlt: { ko: "확대/축소 설명", en: "Zoom explanation" },
        targetZone: "canvas",
        shortcutKey: "Ctrl",
        troubleshootTip: { ko: "Mac에서는 Cmd, Windows에서는 Ctrl을 사용하세요. 트랙패드라면 핀치 제스처로도 확대/축소할 수 있어요.", en: "Use Cmd on Mac, Ctrl on Windows. On trackpad, you can also use pinch gestures to zoom." },
      },
      {
        id: 8,
        type: "action",
        instruction: { ko: "'이동 도구' (화살표 아이콘)를 클릭하거나 'V'를 눌러 선택 모드로 전환하세요.", en: "Click the 'Move tool' (arrow icon) or press 'V' to switch to selection mode." },
        buttonText: { ko: "이동 도구 선택!", en: "Move tool selected!" },
        imageAlt: { ko: "이동 도구", en: "Move tool" },
        targetZone: "toolbar-top",
        shortcutKey: "V",
        troubleshootTip: { ko: "V를 누르거나 상단 툴바 가장 왼쪽의 화살표 아이콘을 클릭하세요. 이 도구로 요소를 선택하고 이동할 수 있어요.", en: "Press V or click the arrow icon at the far left of the top toolbar. This tool lets you select and move elements." },
      },
      {
        id: 9,
        type: "action",
        instruction: { ko: "사각형을 클릭하고 이리저리 움직여보세요.", en: "Click the rectangle and move it around." },
        buttonText: { ko: "이동 완료!", en: "Moved!" },
        imageAlt: { ko: "사각형 이동", en: "Moving rectangle" },
        targetZone: "canvas",
        troubleshootTip: { ko: "사각형을 클릭해서 선택한 후 드래그하세요. 화살표 키로도 1px씩 이동할 수 있어요 (Shift+화살표는 10px).", en: "Click to select the rectangle, then drag. Arrow keys move 1px at a time (Shift+arrows move 10px)." },
      },
      {
        id: 10,
        type: "action",
        instruction: { ko: "Ctrl/Cmd + 스크롤로 사각형을 확대해서 자세히 살펴보세요.", en: "Zoom in on the rectangle using Ctrl/Cmd + scroll." },
        buttonText: { ko: "확대 완료!", en: "Zoomed in!" },
        imageAlt: { ko: "확대 연습", en: "Zoom practice" },
        targetZone: "canvas",
        shortcutKey: "Ctrl",
        troubleshootTip: { ko: "마우스 커서가 있는 위치를 중심으로 확대됩니다. 사각형 위에 커서를 두고 스크롤하면 사각형이 커지는 것처럼 보여요.", en: "Zoom centers on the cursor position. Place cursor over the rectangle and scroll to see it appear larger." },
      },
    ],
  },
  {
    day: 3,
    title: { ko: "도형 마스터", en: "Shape Master" },
    subtitle: { ko: "다양한 도형과 라운딩을 배워보세요", en: "Learn various shapes and rounding" },
    steps: [
      {
        id: 1,
        type: "action",
        instruction: { ko: "새 프레임을 만드세요 (F 누르기).", en: "Create a new frame (Press F)." },
        buttonText: { ko: "프레임 생성!", en: "Frame created!" },
        imageAlt: { ko: "새 프레임 생성", en: "Creating new frame" },
        targetZone: "canvas",
        shortcutKey: "F",
        troubleshootTip: { ko: "F를 누르고 캔버스의 빈 공간에서 드래그하세요. 기존 프레임 밖에 새 프레임을 만들어야 해요.", en: "Press F and drag on an empty area of the canvas. Create the new frame outside existing frames." },
      },
      {
        id: 2,
        type: "action",
        instruction: { ko: "사각형을 그리세요 (R 누르기).", en: "Draw a rectangle (Press R)." },
        buttonText: { ko: "사각형 완성!", en: "Rectangle done!" },
        imageAlt: { ko: "사각형 그리기", en: "Drawing rectangle" },
        targetZone: "canvas",
        shortcutKey: "R",
        troubleshootTip: { ko: "R을 누르고 새로 만든 프레임 안에서 드래그하세요.", en: "Press R and drag inside the frame you just created." },
      },
      {
        id: 3,
        type: "action",
        instruction: { ko: "사각형을 선택하고 오른쪽 패널의 'Corner radius' 섹션을 확인하세요.", en: "Select the rectangle and check 'Corner radius' section in the right panel." },
        buttonText: { ko: "확인했어요!", en: "Found it!" },
        imageAlt: { ko: "Corner radius 섹션", en: "Corner radius section" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "사각형을 클릭해서 선택한 상태에서 오른쪽 패널을 스크롤하세요. 'Corner radius' 또는 모서리 아이콘을 찾으세요.", en: "With the rectangle selected, scroll the right panel. Look for 'Corner radius' or the corner icon." },
      },
      {
        id: 4,
        type: "quiz",
        question: { ko: "'Corner Radius' 아이콘은 어떻게 생겼나요?", en: "What does the 'Corner Radius' icon look like?" },
        options: [
          { ko: "직선 모서리", en: "Straight corner" },
          { ko: "둥근 모서리 모양", en: "Rounded corner shape" },
          { ko: "원형", en: "Circle" }
        ],
        correctIndex: 1,
        successMessage: { ko: "맞아요! 둥근 모서리 아이콘이 Corner Radius예요.", en: "Right! The rounded corner icon is Corner Radius." },
        imageAlt: { ko: "Corner Radius 아이콘", en: "Corner Radius icon" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "오른쪽 패널에서 작은 둥근 모서리 아이콘을 찾으세요. 숫자 입력 필드 옆에 있어요.", en: "Find the small rounded corner icon in the right panel. It's next to the number input field." },
      },
      {
        id: 5,
        type: "action",
        instruction: { ko: "반지름 박스에 '20'을 입력하세요. 모서리가 둥글어지는 걸 확인하세요!", en: "Enter '20' in the radius box. Watch the corners become rounded!" },
        buttonText: { ko: "라운딩 적용!", en: "Rounding applied!" },
        imageAlt: { ko: "라운딩 적용", en: "Applying rounding" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "숫자를 입력한 후 Enter를 눌러야 적용됩니다. 모서리가 안 둥글어지면 사각형이 선택되어 있는지 확인하세요.", en: "Press Enter after typing the number to apply. If corners don't round, check if the rectangle is selected." },
      },
      {
        id: 6,
        type: "action",
        instruction: { ko: "'O'를 누르세요 (원/타원 도구).", en: "Press 'O' (Ellipse tool)." },
        buttonText: { ko: "'O' 눌렀어요!", en: "Pressed 'O'!" },
        imageAlt: { ko: "O 키 - 원 도구", en: "O key - Ellipse tool" },
        targetZone: "toolbar-top",
        shortcutKey: "O",
        troubleshootTip: { ko: "O를 누르면 상단 툴바에서 Ellipse 도구가 선택됩니다.", en: "Pressing O selects the Ellipse tool in the top toolbar." },
      },
      {
        id: 7,
        type: "quiz",
        question: { ko: "완벽한 정원을 그리려면 어떤 키를 누른 채로 그려야 할까요?", en: "Which key should you hold to draw a perfect circle?" },
        options: [
          { ko: "Ctrl", en: "Ctrl" },
          { ko: "Alt", en: "Alt" },
          { ko: "Shift", en: "Shift" }
        ],
        correctIndex: 2,
        successMessage: { ko: "정답! Shift를 누르면 비율이 고정돼요.", en: "Correct! Holding Shift locks the aspect ratio." },
        imageAlt: { ko: "Shift 키", en: "Shift key" },
        targetZone: "canvas",
        shortcutKey: "Shift",
        troubleshootTip: { ko: "Shift 키는 비율을 1:1로 고정해요. 사각형을 그릴 때도 Shift를 누르면 정사각형이 됩니다.", en: "Shift locks the ratio to 1:1. Holding Shift while drawing rectangles also makes perfect squares." },
      },
      {
        id: 8,
        type: "action",
        instruction: { ko: "'Shift'를 누른 채로 그려서 완벽한 원을 만드세요.", en: "Hold 'Shift' while drawing to make a perfect circle." },
        buttonText: { ko: "정원 완성!", en: "Circle done!" },
        imageAlt: { ko: "정원 그리기", en: "Drawing a circle" },
        targetZone: "canvas",
        shortcutKey: "Shift",
        troubleshootTip: { ko: "Shift를 먼저 누르고, 누른 상태로 드래그하세요. 드래그 중간에 Shift를 누르면 안 돼요.", en: "Press Shift first, then drag while holding. Don't press Shift in the middle of dragging." },
      },
      {
        id: 9,
        type: "action",
        instruction: { ko: "원을 사각형 위에 배치하세요.", en: "Place the circle on top of the rectangle." },
        buttonText: { ko: "배치 완료!", en: "Placed!" },
        imageAlt: { ko: "원 배치", en: "Placing circle" },
        targetZone: "canvas",
        troubleshootTip: { ko: "V를 눌러 선택 도구로 전환한 후 원을 드래그해서 사각형 위로 옮기세요.", en: "Press V to switch to selection tool, then drag the circle onto the rectangle." },
      },
      {
        id: 10,
        type: "action",
        instruction: { ko: "두 도형을 모두 선택하고 모서리를 드래그하여 크기를 조절해보세요.", en: "Select both shapes and drag a corner to resize them." },
        buttonText: { ko: "크기 조절 완료!", en: "Resized!" },
        imageAlt: { ko: "크기 조절", en: "Resizing" },
        targetZone: "canvas",
        shortcutKey: "Shift",
        troubleshootTip: { ko: "여러 요소를 선택하려면 Shift를 누른 채로 클릭하거나, 드래그해서 여러 요소를 감싸세요.", en: "To select multiple elements, hold Shift and click, or drag to encompass multiple elements." },
      },
    ],
  },
  {
    day: 4,
    title: { ko: "타이포그래피 마법", en: "Typography Magic" },
    subtitle: { ko: "텍스트의 세계를 탐험하세요", en: "Explore the world of text" },
    steps: [
      {
        id: 1,
        type: "action",
        instruction: { ko: "'T'를 누르세요 (텍스트 도구).", en: "Press 'T' (Text tool)." },
        buttonText: { ko: "'T' 눌렀어요!", en: "Pressed 'T'!" },
        imageAlt: { ko: "T 키 - 텍스트 도구", en: "T key - Text tool" },
        targetZone: "toolbar-top",
        shortcutKey: "T",
        troubleshootTip: { ko: "T를 누르면 커서가 텍스트 입력 모양으로 바뀌어요. 상단 툴바에서 T 아이콘이 선택되어 있는지 확인하세요.", en: "Pressing T changes the cursor to text input mode. Check if the T icon is selected in the top toolbar." },
      },
      {
        id: 2,
        type: "action",
        instruction: { ko: "아무 곳이나 클릭하고 'Hello Figma'를 입력하세요.", en: "Click anywhere and type 'Hello Figma'." },
        buttonText: { ko: "텍스트 입력!", en: "Text entered!" },
        imageAlt: { ko: "텍스트 입력", en: "Entering text" },
        targetZone: "canvas",
        troubleshootTip: { ko: "클릭하면 텍스트 입력 모드가 됩니다. 바로 타이핑을 시작하세요. 클릭 대신 드래그하면 텍스트 박스 너비가 고정돼요.", en: "Clicking enters text input mode. Start typing immediately. Dragging instead of clicking sets a fixed text box width." },
      },
      {
        id: 3,
        type: "action",
        instruction: { ko: "텍스트를 드래그하여 전체 선택하세요.", en: "Drag to select all the text." },
        buttonText: { ko: "선택 완료!", en: "Selected!" },
        imageAlt: { ko: "텍스트 선택", en: "Selecting text" },
        targetZone: "canvas",
        shortcutKey: "Ctrl + A",
        troubleshootTip: { ko: "텍스트를 더블클릭해서 편집 모드로 들어간 후 Ctrl/Cmd + A를 누르면 전체 선택됩니다.", en: "Double-click the text to enter edit mode, then press Ctrl/Cmd + A to select all." },
      },
      {
        id: 4,
        type: "quiz",
        question: { ko: "텍스트 속성을 수정하려면 어느 패널의 어느 섹션을 봐야 할까요?", en: "Which panel and section should you look at to modify text properties?" },
        options: [
          { ko: "왼쪽 패널 - Layers", en: "Left Panel - Layers" },
          { ko: "오른쪽 패널 - Text", en: "Right Panel - Text" },
          { ko: "상단 바 - Tools", en: "Top Bar - Tools" }
        ],
        correctIndex: 1,
        successMessage: { ko: "맞아요! 오른쪽 패널의 Text 섹션에서 모든 텍스트 속성을 수정해요.", en: "Right! You modify all text properties in the Text section of the right panel." },
        imageAlt: { ko: "Text 섹션", en: "Text section" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "텍스트를 선택하면 오른쪽 패널에 'Text' 섹션이 나타나요. 폰트, 크기, 정렬 등을 변경할 수 있어요.", en: "When text is selected, the 'Text' section appears in the right panel. You can change font, size, alignment, etc." },
      },
      {
        id: 5,
        type: "action",
        instruction: { ko: "폰트를 'Inter'에서 'Roboto' (또는 다른 폰트)로 변경하세요.", en: "Change the font from 'Inter' to 'Roboto' (or another font)." },
        buttonText: { ko: "폰트 변경!", en: "Font changed!" },
        imageAlt: { ko: "폰트 변경", en: "Changing font" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "폰트 이름을 클릭하면 폰트 목록이 나타나요. 검색창에 원하는 폰트 이름을 입력해서 찾을 수 있어요.", en: "Click the font name to see the font list. You can search for fonts by typing in the search box." },
      },
      {
        id: 6,
        type: "action",
        instruction: { ko: "'Regular'를 'Bold'로 변경하세요.", en: "Change 'Regular' to 'Bold'." },
        buttonText: { ko: "굵기 변경!", en: "Weight changed!" },
        imageAlt: { ko: "굵기 변경", en: "Changing weight" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "폰트 이름 옆의 'Regular' 드롭다운을 클릭하세요. Bold, Medium, Light 등 다양한 옵션이 있어요.", en: "Click the 'Regular' dropdown next to the font name. You'll find Bold, Medium, Light, and other options." },
      },
      {
        id: 7,
        type: "action",
        instruction: { ko: "폰트 크기를 48로 변경하세요.", en: "Change the font size to 48." },
        buttonText: { ko: "크기 변경!", en: "Size changed!" },
        imageAlt: { ko: "크기 변경", en: "Changing size" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "폰트 크기 숫자를 클릭하고 48을 입력한 후 Enter를 누르세요.", en: "Click the font size number, type 48, and press Enter." },
      },
      {
        id: 8,
        type: "action",
        instruction: { ko: "색상 사각형(Fill)을 클릭하고 파란색을 선택하세요.", en: "Click the color square (Fill) and choose blue." },
        buttonText: { ko: "색상 변경!", en: "Color changed!" },
        imageAlt: { ko: "색상 변경", en: "Changing color" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "텍스트의 Fill 색상은 Text 섹션이 아닌 Fill 섹션에 있어요. 오른쪽 패널을 스크롤해서 찾으세요.", en: "Text Fill color is in the Fill section, not the Text section. Scroll the right panel to find it." },
      },
      {
        id: 9,
        type: "quiz",
        question: { ko: "텍스트를 가운데 정렬하려면 어디를 클릭해야 할까요?", en: "Where should you click to center-align text?" },
        options: [
          { ko: "왼쪽 정렬 아이콘", en: "Left align icon" },
          { ko: "가운데 정렬 아이콘", en: "Center align icon" },
          { ko: "Fill 색상", en: "Fill color" }
        ],
        correctIndex: 1,
        successMessage: { ko: "정답! 정렬 아이콘으로 텍스트 정렬을 바꿀 수 있어요.", en: "Correct! You can change text alignment with the alignment icons." },
        imageAlt: { ko: "텍스트 정렬", en: "Text alignment" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "Text 섹션에서 정렬 아이콘들을 찾으세요. 왼쪽, 가운데, 오른쪽, 양쪽 정렬 옵션이 있어요.", en: "Find the alignment icons in the Text section. There are left, center, right, and justify options." },
      },
      {
        id: 10,
        type: "action",
        instruction: { ko: "정렬 아이콘을 사용하여 텍스트를 가운데 정렬하세요.", en: "Use the alignment icon to center-align the text." },
        buttonText: { ko: "정렬 완료!", en: "Aligned!" },
        imageAlt: { ko: "가운데 정렬", en: "Center alignment" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "가운데 정렬 아이콘은 가로선들이 가운데로 모인 모양이에요.", en: "The center align icon looks like horizontal lines centered together." },
      },
    ],
  },
  {
    day: 5,
    title: { ko: "색상 & 이미지", en: "Colors & Images" },
    subtitle: { ko: "시각적 요소를 다루어보세요", en: "Work with visual elements" },
    steps: [
      {
        id: 1,
        type: "action",
        instruction: { ko: "사각형을 그리세요.", en: "Draw a rectangle." },
        buttonText: { ko: "사각형 완성!", en: "Rectangle done!" },
        imageAlt: { ko: "사각형 그리기", en: "Drawing rectangle" },
        targetZone: "canvas",
        shortcutKey: "R",
        troubleshootTip: { ko: "R을 눌러 사각형 도구를 선택하고 캔버스에서 드래그하세요.", en: "Press R to select rectangle tool and drag on the canvas." },
      },
      {
        id: 2,
        type: "action",
        instruction: { ko: "오른쪽 패널에서 'Fill' 색상 사각형을 클릭하세요.", en: "Click the 'Fill' color square in the right panel." },
        buttonText: { ko: "Fill 클릭!", en: "Clicked Fill!" },
        imageAlt: { ko: "Fill 클릭", en: "Clicking Fill" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "사각형을 선택한 상태에서 오른쪽 패널의 Fill 섹션을 찾으세요. 색상 미리보기 사각형을 클릭하면 컬러 피커가 열려요.", en: "With rectangle selected, find Fill section in right panel. Click the color preview square to open color picker." },
      },
      {
        id: 3,
        type: "action",
        instruction: { ko: "색상 피커를 빨간색으로 드래그해보세요.", en: "Drag the color picker to red." },
        buttonText: { ko: "빨간색 선택!", en: "Red selected!" },
        imageAlt: { ko: "빨간색 선택", en: "Selecting red" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "컬러 피커에서 왼쪽의 색상 막대를 빨간색 영역으로 드래그하고, 중앙의 큰 영역에서 원하는 밝기/채도를 선택하세요.", en: "Drag the color bar on the left to red, then select desired brightness/saturation in the center area." },
      },
      {
        id: 4,
        type: "quiz",
        question: { ko: "그라데이션(Gradient)을 적용하려면 'Solid' 대신 무엇을 선택해야 할까요?", en: "To apply a gradient, what should you select instead of 'Solid'?" },
        options: [
          { ko: "Image", en: "Image" },
          { ko: "Linear", en: "Linear" },
          { ko: "None", en: "None" }
        ],
        correctIndex: 1,
        successMessage: { ko: "맞아요! Linear는 선형 그라데이션을 의미해요.", en: "Right! Linear means a linear gradient." },
        imageAlt: { ko: "그라데이션 설명", en: "Gradient explanation" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "컬러 피커 상단에 'Solid'라고 적힌 드롭다운이 있어요. 클릭하면 Linear, Radial 등의 그라데이션 옵션이 나와요.", en: "There's a dropdown labeled 'Solid' at the top of the color picker. Click it to see Linear, Radial, and other gradient options." },
      },
      {
        id: 5,
        type: "action",
        instruction: { ko: "색상 창 상단의 'Solid' → 'Linear' (그라데이션)으로 변경하세요.", en: "Change 'Solid' to 'Linear' (gradient) at the top of the color window." },
        buttonText: { ko: "그라데이션 적용!", en: "Gradient applied!" },
        imageAlt: { ko: "그라데이션 적용", en: "Applying gradient" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "Linear를 선택하면 캔버스의 사각형에 그라데이션 핸들이 나타나요. 드래그해서 방향을 바꿀 수 있어요.", en: "Selecting Linear shows gradient handles on the rectangle in the canvas. Drag them to change direction." },
      },
      {
        id: 6,
        type: "action",
        instruction: { ko: "오른쪽 패널에서 'Stroke' (테두리)를 추가하세요.", en: "Add 'Stroke' (border) in the right panel." },
        buttonText: { ko: "Stroke 추가!", en: "Stroke added!" },
        imageAlt: { ko: "Stroke 추가", en: "Adding Stroke" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "Stroke 섹션 옆의 + 버튼을 클릭하세요. 없다면 Fill 아래쪽을 확인해보세요.", en: "Click the + button next to Stroke section. If not visible, check below the Fill section." },
      },
      {
        id: 7,
        type: "action",
        instruction: { ko: "Stroke 크기를 10으로 설정하세요.", en: "Set Stroke size to 10." },
        buttonText: { ko: "크기 설정!", en: "Size set!" },
        imageAlt: { ko: "Stroke 크기", en: "Stroke size" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "Stroke 섹션에서 숫자를 클릭하고 10을 입력한 후 Enter를 누르세요.", en: "Click the number in Stroke section, type 10, and press Enter." },
      },
      {
        id: 8,
        type: "action",
        instruction: { ko: "컴퓨터에서 이미지를 찾아 Figma 캔버스로 드래그 앤 드롭하세요.", en: "Find an image on your computer and drag & drop it onto the Figma canvas." },
        buttonText: { ko: "이미지 추가!", en: "Image added!" },
        imageAlt: { ko: "이미지 드래그", en: "Dragging image" },
        targetZone: "canvas",
        troubleshootTip: { ko: "파일 탐색기에서 이미지 파일을 Figma 창으로 직접 드래그하세요. PNG, JPG, SVG 등 다양한 형식을 지원해요.", en: "Drag an image file directly from file explorer to Figma window. PNG, JPG, SVG, and other formats are supported." },
      },
      {
        id: 9,
        type: "quiz",
        question: { ko: "이미지 비율을 유지하면서 크기를 조절하려면 어떤 키를 눌러야 할까요?", en: "Which key should you hold to resize while maintaining aspect ratio?" },
        options: [
          { ko: "Ctrl", en: "Ctrl" },
          { ko: "Alt", en: "Alt" },
          { ko: "Shift", en: "Shift" }
        ],
        correctIndex: 2,
        successMessage: { ko: "정답! Shift를 누르면 비율이 고정돼요.", en: "Correct! Holding Shift locks the aspect ratio." },
        imageAlt: { ko: "Shift 키 설명", en: "Shift key explanation" },
        targetZone: "canvas",
        shortcutKey: "Shift",
        troubleshootTip: { ko: "Shift 없이 모서리를 드래그하면 이미지가 찌그러질 수 있어요. 항상 Shift를 누른 채로 크기를 조절하세요.", en: "Dragging corners without Shift can distort the image. Always hold Shift when resizing." },
      },
      {
        id: 10,
        type: "action",
        instruction: { ko: "Shift를 눌러 비율을 유지하면서 이미지 크기를 조절하세요.", en: "Hold Shift and resize the image while maintaining proportions." },
        buttonText: { ko: "크기 조절 완료!", en: "Resized!" },
        imageAlt: { ko: "이미지 크기 조절", en: "Resizing image" },
        targetZone: "canvas",
        shortcutKey: "Shift",
        troubleshootTip: { ko: "이미지의 모서리 핸들을 Shift를 누른 채로 드래그하세요.", en: "Drag the corner handles of the image while holding Shift." },
      },
    ],
  },
  {
    day: 6,
    title: { ko: "그룹 & 정렬", en: "Groups & Alignment" },
    subtitle: { ko: "요소들을 체계적으로 정리하세요", en: "Organize elements systematically" },
    steps: [
      {
        id: 1,
        type: "action",
        instruction: { ko: "서로 다른 사각형 3개를 그리세요.", en: "Draw 3 different rectangles." },
        buttonText: { ko: "사각형 3개 완성!", en: "3 rectangles done!" },
        imageAlt: { ko: "사각형 3개", en: "3 rectangles" },
        targetZone: "canvas",
        shortcutKey: "R",
        troubleshootTip: { ko: "R을 눌러 사각형을 하나 그리고, 다시 R을 눌러 다른 위치에 사각형을 그리세요. 3번 반복하세요.", en: "Press R to draw one rectangle, then R again to draw another in a different location. Repeat 3 times." },
      },
      {
        id: 2,
        type: "action",
        instruction: { ko: "모두 선택하세요 (드래그하여 선택).", en: "Select all of them (drag to select)." },
        buttonText: { ko: "모두 선택!", en: "All selected!" },
        imageAlt: { ko: "모두 선택", en: "Selecting all" },
        targetZone: "canvas",
        troubleshootTip: { ko: "V를 눌러 선택 도구로 전환한 후, 세 사각형을 모두 포함하도록 드래그하세요.", en: "Press V to switch to selection tool, then drag to encompass all three rectangles." },
      },
      {
        id: 3,
        type: "quiz",
        question: { ko: "선택한 요소들을 그룹화하는 단축키는 무엇일까요?", en: "What's the shortcut to group selected elements?" },
        options: [
          { ko: "Ctrl + G", en: "Ctrl + G" },
          { ko: "Ctrl + A", en: "Ctrl + A" },
          { ko: "Ctrl + C", en: "Ctrl + C" }
        ],
        correctIndex: 0,
        successMessage: { ko: "맞아요! Ctrl(Cmd) + G로 그룹화할 수 있어요.", en: "Right! You can group with Ctrl(Cmd) + G." },
        imageAlt: { ko: "그룹화 단축키", en: "Grouping shortcut" },
        targetZone: "canvas",
        shortcutKey: "Ctrl + G",
        troubleshootTip: { ko: "Mac에서는 Cmd + G, Windows에서는 Ctrl + G를 사용하세요.", en: "Use Cmd + G on Mac, Ctrl + G on Windows." },
      },
      {
        id: 4,
        type: "action",
        instruction: { ko: "'Ctrl + G' (또는 Cmd + G)를 눌러 그룹화하세요.", en: "Press 'Ctrl + G' (or Cmd + G) to group." },
        buttonText: { ko: "그룹화 완료!", en: "Grouped!" },
        imageAlt: { ko: "그룹화", en: "Grouping" },
        targetZone: "canvas",
        shortcutKey: "Ctrl + G",
        troubleshootTip: { ko: "세 요소가 모두 선택된 상태에서 단축키를 누르세요. 왼쪽 레이어 패널에서 'Group'이 생성되는지 확인하세요.", en: "Press the shortcut with all three elements selected. Check if 'Group' appears in the left Layers panel." },
      },
      {
        id: 5,
        type: "action",
        instruction: { ko: "왼쪽 패널을 확인하세요 → 'Group 1'이 보입니다.", en: "Check the left panel → You should see 'Group 1'." },
        buttonText: { ko: "확인했어요!", en: "Confirmed!" },
        imageAlt: { ko: "Group 1", en: "Group 1" },
        targetZone: "sidebar-left",
        troubleshootTip: { ko: "레이어 패널에서 'Group' 레이어를 클릭하면 하위 요소들이 접히거나 펼쳐져요.", en: "Click the 'Group' layer in the Layers panel to collapse or expand its children." },
      },
      {
        id: 6,
        type: "action",
        instruction: { ko: "그룹을 이동하세요. 함께 움직이는 것을 확인하세요!", en: "Move the group. Watch them move together!" },
        buttonText: { ko: "그룹 이동!", en: "Group moved!" },
        imageAlt: { ko: "그룹 이동", en: "Moving group" },
        targetZone: "canvas",
        troubleshootTip: { ko: "그룹을 선택하고 드래그하면 내부의 모든 요소가 함께 이동해요.", en: "When you select and drag a group, all elements inside move together." },
      },
      {
        id: 7,
        type: "action",
        instruction: { ko: "그룹 해제하세요 (Ctrl + Shift + G).", en: "Ungroup (Ctrl + Shift + G)." },
        buttonText: { ko: "그룹 해제!", en: "Ungrouped!" },
        imageAlt: { ko: "그룹 해제", en: "Ungrouping" },
        targetZone: "canvas",
        shortcutKey: "Ctrl + Shift + G",
        troubleshootTip: { ko: "그룹이 선택된 상태에서 Ctrl(Cmd) + Shift + G를 누르세요.", en: "With the group selected, press Ctrl(Cmd) + Shift + G." },
      },
      {
        id: 8,
        type: "action",
        instruction: { ko: "3개를 다시 모두 선택하세요.", en: "Select all 3 again." },
        buttonText: { ko: "다시 선택!", en: "Selected again!" },
        imageAlt: { ko: "다시 선택", en: "Selecting again" },
        targetZone: "canvas",
        troubleshootTip: { ko: "드래그해서 선택하거나 Shift를 누른 채로 하나씩 클릭하세요.", en: "Drag to select or hold Shift and click each one." },
      },
      {
        id: 9,
        type: "quiz",
        question: { ko: "요소들을 균등하게 정렬하려면 어떤 도구를 사용해야 할까요?", en: "Which tool should you use to evenly align elements?" },
        options: [
          { ko: "그룹화", en: "Grouping" },
          { ko: "Tidy Up / 정렬 도구", en: "Tidy Up / Alignment tools" },
          { ko: "복제", en: "Duplicate" }
        ],
        correctIndex: 1,
        successMessage: { ko: "맞아요! Tidy Up이나 정렬 도구로 요소들을 깔끔하게 배치할 수 있어요.", en: "Right! Tidy Up or alignment tools let you arrange elements neatly." },
        imageAlt: { ko: "정렬 도구", en: "Alignment tools" },
        targetZone: "toolbar-top",
        troubleshootTip: { ko: "여러 요소를 선택하면 선택 영역 우하단에 Tidy Up 아이콘이 나타나요.", en: "When multiple elements are selected, a Tidy Up icon appears at the bottom right of the selection." },
      },
      {
        id: 10,
        type: "action",
        instruction: { ko: "정렬 도구를 사용하여 사각형들을 상단 정렬하세요.", en: "Use alignment tools to top-align the rectangles." },
        buttonText: { ko: "상단 정렬 완료!", en: "Top aligned!" },
        imageAlt: { ko: "상단 정렬", en: "Top alignment" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "오른쪽 패널 상단의 정렬 아이콘들 중 'Align top' 아이콘을 클릭하세요.", en: "Click the 'Align top' icon among the alignment icons at the top of the right panel." },
      },
    ],
  },
  {
    day: 7,
    title: { ko: "오토 레이아웃", en: "Auto Layout" },
    subtitle: { ko: "자동으로 정렬되는 마법을 배워보세요", en: "Learn the magic of automatic alignment" },
    steps: [
      {
        id: 1,
        type: "action",
        instruction: { ko: "'T'를 누르고 'Button'이라고 입력하세요.", en: "Press 'T' and type 'Button'." },
        buttonText: { ko: "텍스트 입력!", en: "Text entered!" },
        imageAlt: { ko: "Button 텍스트", en: "Button text" },
        targetZone: "canvas",
        shortcutKey: "T",
        troubleshootTip: { ko: "T를 누르고 캔버스를 클릭한 후 'Button'을 입력하세요.", en: "Press T, click the canvas, then type 'Button'." },
      },
      {
        id: 2,
        type: "action",
        instruction: { ko: "텍스트를 선택하고 'Shift + A'를 누르세요 (오토 레이아웃 추가).", en: "Select the text and press 'Shift + A' (add Auto Layout)." },
        buttonText: { ko: "오토 레이아웃 적용!", en: "Auto Layout applied!" },
        imageAlt: { ko: "Shift + A", en: "Shift + A" },
        targetZone: "canvas",
        shortcutKey: "Shift + A",
        troubleshootTip: { ko: "텍스트를 선택한 상태에서 Shift + A를 누르세요. 텍스트 주위에 프레임이 생겨요.", en: "With text selected, press Shift + A. A frame will appear around the text." },
      },
      {
        id: 3,
        type: "quiz",
        question: { ko: "오토 레이아웃을 적용하면 무엇이 생기나요?", en: "What happens when you apply Auto Layout?" },
        options: [
          { ko: "색상이 바뀐다", en: "Color changes" },
          { ko: "텍스트 주위에 프레임이 생긴다", en: "A frame appears around the text" },
          { ko: "텍스트가 사라진다", en: "Text disappears" }
        ],
        correctIndex: 1,
        successMessage: { ko: "맞아요! 오토 레이아웃은 요소 주위에 스마트한 프레임을 만들어요.", en: "Right! Auto Layout creates a smart frame around elements." },
        imageAlt: { ko: "오토 레이아웃 프레임", en: "Auto Layout frame" },
        targetZone: "sidebar-left",
        troubleshootTip: { ko: "왼쪽 레이어 패널을 보면 텍스트가 새 Frame 안에 들어간 것을 확인할 수 있어요.", en: "In the left Layers panel, you can see the text is now inside a new Frame." },
      },
      {
        id: 4,
        type: "action",
        instruction: { ko: "새로 생긴 프레임을 선택하고 Fill 색상을 추가하세요.", en: "Select the new frame and add a Fill color." },
        buttonText: { ko: "색상 추가!", en: "Color added!" },
        imageAlt: { ko: "Fill 색상 추가", en: "Adding Fill color" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "프레임을 선택하고 오른쪽 패널 Fill 섹션의 + 버튼을 클릭하세요.", en: "Select the frame and click the + button in the Fill section of the right panel." },
      },
      {
        id: 5,
        type: "action",
        instruction: { ko: "오른쪽 'Auto Layout' 패널에서 'Horizontal padding'을 24로 변경하세요.", en: "Change 'Horizontal padding' to 24 in the right 'Auto Layout' panel." },
        buttonText: { ko: "패딩 변경!", en: "Padding changed!" },
        imageAlt: { ko: "Horizontal padding", en: "Horizontal padding" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "Auto Layout 섹션에서 좌우 패딩 값을 찾아 24를 입력하세요.", en: "Find the horizontal padding value in Auto Layout section and enter 24." },
      },
      {
        id: 6,
        type: "action",
        instruction: { ko: "'Vertical padding'을 12로 변경하세요.", en: "Change 'Vertical padding' to 12." },
        buttonText: { ko: "수직 패딩 변경!", en: "Vertical padding changed!" },
        imageAlt: { ko: "Vertical padding", en: "Vertical padding" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "상하 패딩 값을 12로 변경하세요.", en: "Change the top/bottom padding value to 12." },
      },
      {
        id: 7,
        type: "action",
        instruction: { ko: "Corner Radius를 8로 설정하세요. 버튼이 완성되었어요!", en: "Set Corner Radius to 8. Your button is complete!" },
        buttonText: { ko: "버튼 완성!", en: "Button complete!" },
        imageAlt: { ko: "버튼 완성", en: "Button complete" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "프레임의 Corner radius 값을 8로 변경하세요.", en: "Change the frame's Corner radius value to 8." },
      },
      {
        id: 8,
        type: "action",
        instruction: { ko: "텍스트를 더블클릭해서 'Click Me!'로 변경해보세요. 버튼이 자동으로 커지나요?", en: "Double-click the text and change it to 'Click Me!'. Does the button grow automatically?" },
        buttonText: { ko: "텍스트 변경!", en: "Text changed!" },
        imageAlt: { ko: "텍스트 변경", en: "Changing text" },
        targetZone: "canvas",
        troubleshootTip: { ko: "오토 레이아웃 덕분에 텍스트 길이에 따라 버튼 크기가 자동 조절돼요. 이게 오토 레이아웃의 마법이에요!", en: "Thanks to Auto Layout, button size adjusts automatically based on text length. That's the magic of Auto Layout!" },
      },
      {
        id: 9,
        type: "action",
        instruction: { ko: "버튼을 복제하세요 (Alt + 드래그).", en: "Duplicate the button (Alt + drag)." },
        buttonText: { ko: "복제 완료!", en: "Duplicated!" },
        imageAlt: { ko: "버튼 복제", en: "Duplicating button" },
        targetZone: "canvas",
        shortcutKey: "Alt",
        troubleshootTip: { ko: "Alt(Option)를 누른 채로 버튼을 드래그하면 복제됩니다.", en: "Hold Alt(Option) and drag the button to duplicate it." },
      },
      {
        id: 10,
        type: "action",
        instruction: { ko: "두 버튼을 모두 선택하고 'Shift + A'를 다시 누르세요 (버튼 리스트 만들기).", en: "Select both buttons and press 'Shift + A' again (create button list)." },
        buttonText: { ko: "버튼 리스트 완성!", en: "Button list complete!" },
        imageAlt: { ko: "버튼 리스트", en: "Button list" },
        targetZone: "canvas",
        shortcutKey: "Shift + A",
        troubleshootTip: { ko: "두 버튼을 선택한 상태에서 Shift + A를 누르면 오토 레이아웃 리스트가 만들어져요.", en: "With both buttons selected, press Shift + A to create an Auto Layout list." },
      },
    ],
  },
  {
    day: 8,
    title: { ko: "컴포넌트", en: "Components" },
    subtitle: { ko: "재사용 가능한 디자인 요소를 만드세요", en: "Create reusable design elements" },
    steps: [
      {
        id: 1,
        type: "action",
        instruction: { ko: "Day 7에서 만든 버튼을 선택하세요 (없다면 새로 만드세요).", en: "Select the button from Day 7 (create one if needed)." },
        buttonText: { ko: "버튼 선택!", en: "Button selected!" },
        imageAlt: { ko: "버튼 선택", en: "Selecting button" },
        targetZone: "canvas",
        troubleshootTip: { ko: "오토 레이아웃이 적용된 버튼이 필요해요. T로 텍스트를 만들고 Shift+A로 오토 레이아웃을 적용하세요.", en: "You need a button with Auto Layout. Create text with T and apply Auto Layout with Shift+A." },
      },
      {
        id: 2,
        type: "action",
        instruction: { ko: "상단 가운데 툴바에서 다이아몬드 아이콘 (Create Component)을 클릭하세요.", en: "Click the diamond icon (Create Component) in the center of the top toolbar." },
        buttonText: { ko: "컴포넌트 생성!", en: "Component created!" },
        imageAlt: { ko: "Create Component", en: "Create Component" },
        targetZone: "toolbar-top",
        shortcutKey: "Ctrl + Alt + K",
        troubleshootTip: { ko: "상단 툴바 중앙에 있는 다이아몬드 모양 아이콘을 찾으세요. 또는 Ctrl(Cmd) + Alt + K를 누르세요.", en: "Find the diamond-shaped icon in the center of the top toolbar. Or press Ctrl(Cmd) + Alt + K." },
      },
      {
        id: 3,
        type: "quiz",
        question: { ko: "컴포넌트로 만들면 테두리 색이 어떻게 변하나요?", en: "How does the border color change when you make a component?" },
        options: [
          { ko: "파란색", en: "Blue" },
          { ko: "보라색", en: "Purple" },
          { ko: "초록색", en: "Green" }
        ],
        correctIndex: 1,
        successMessage: { ko: "맞아요! 보라색 테두리는 이것이 '마스터' 컴포넌트라는 표시예요.", en: "Right! The purple border indicates this is a 'master' component." },
        imageAlt: { ko: "보라색 테두리", en: "Purple border" },
        targetZone: "canvas",
        troubleshootTip: { ko: "컴포넌트가 되면 선택 시 보라색 테두리가 보여요. 왼쪽 레이어 패널에서도 다이아몬드 아이콘이 표시돼요.", en: "When it becomes a component, you'll see a purple border when selected. A diamond icon also appears in the left Layers panel." },
      },
      {
        id: 4,
        type: "action",
        instruction: { ko: "Alt를 누른 채로 컴포넌트를 드래그해서 복사본(인스턴스)을 만드세요.", en: "Hold Alt and drag the component to create a copy (instance)." },
        buttonText: { ko: "인스턴스 생성!", en: "Instance created!" },
        imageAlt: { ko: "인스턴스 생성", en: "Creating instance" },
        targetZone: "canvas",
        shortcutKey: "Alt",
        troubleshootTip: { ko: "Alt(Option) + 드래그로 복제하면 인스턴스가 생겨요. 인스턴스는 빈 다이아몬드 아이콘으로 표시돼요.", en: "Alt(Option) + drag creates an instance. Instances show an empty diamond icon." },
      },
      {
        id: 5,
        type: "action",
        instruction: { ko: "인스턴스를 2개 더 만들어서 총 3개의 인스턴스를 만드세요.", en: "Create 2 more instances for a total of 3." },
        buttonText: { ko: "3개 인스턴스 완성!", en: "3 instances done!" },
        imageAlt: { ko: "3개 인스턴스", en: "3 instances" },
        targetZone: "canvas",
        troubleshootTip: { ko: "Alt + 드래그를 반복하거나, 복제 후 Ctrl(Cmd) + D로 같은 간격으로 추가 복제할 수 있어요.", en: "Repeat Alt + drag, or use Ctrl(Cmd) + D after duplicating to duplicate again at the same distance." },
      },
      {
        id: 6,
        type: "action",
        instruction: { ko: "'마스터' 컴포넌트(보라색 채워진 다이아몬드)의 색상을 초록색으로 변경하세요.", en: "Change the color of the 'master' component (filled purple diamond) to green." },
        buttonText: { ko: "색상 변경!", en: "Color changed!" },
        imageAlt: { ko: "마스터 색상 변경", en: "Changing master color" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "마스터 컴포넌트를 선택하고 Fill 색상을 변경하세요.", en: "Select the master component and change the Fill color." },
      },
      {
        id: 7,
        type: "quiz",
        question: { ko: "마스터 컴포넌트의 색상을 바꾸면 인스턴스들은 어떻게 되나요?", en: "What happens to instances when you change the master component's color?" },
        options: [
          { ko: "변하지 않는다", en: "No change" },
          { ko: "모두 같이 바뀐다", en: "They all change together" },
          { ko: "삭제된다", en: "They get deleted" }
        ],
        correctIndex: 1,
        successMessage: { ko: "정답! 마스터를 수정하면 모든 인스턴스가 자동으로 업데이트돼요. 이게 컴포넌트의 힘이에요!", en: "Correct! Editing the master automatically updates all instances. That's the power of components!" },
        imageAlt: { ko: "인스턴스 업데이트", en: "Instance update" },
        targetZone: "canvas",
        troubleshootTip: { ko: "모든 인스턴스가 초록색으로 바뀌었는지 확인하세요.", en: "Check if all instances turned green." },
      },
      {
        id: 8,
        type: "action",
        instruction: { ko: "인스턴스 하나의 텍스트를 'Log in'으로 변경하세요.", en: "Change the text of one instance to 'Log in'." },
        buttonText: { ko: "텍스트 변경!", en: "Text changed!" },
        imageAlt: { ko: "인스턴스 텍스트 변경", en: "Changing instance text" },
        targetZone: "canvas",
        troubleshootTip: { ko: "인스턴스의 텍스트를 더블클릭해서 편집하세요. 텍스트는 개별적으로 변경할 수 있어요.", en: "Double-click the instance's text to edit. Text can be changed individually." },
      },
      {
        id: 9,
        type: "quiz",
        question: { ko: "인스턴스에서 개별적으로 바꿀 수 있는 것은?", en: "What can you change individually in an instance?" },
        options: [
          { ko: "아무것도 못 바꾼다", en: "Nothing" },
          { ko: "텍스트, 색상 등 속성을 개별 변경 가능", en: "Text, color, and other properties" },
          { ko: "크기만 바꿀 수 있다", en: "Only size" }
        ],
        correctIndex: 1,
        successMessage: { ko: "맞아요! 인스턴스는 마스터의 구조를 따르지만, 텍스트나 색상 같은 속성은 개별 수정할 수 있어요.", en: "Right! Instances follow the master's structure, but properties like text and color can be modified individually." },
        imageAlt: { ko: "인스턴스 오버라이드", en: "Instance override" },
        targetZone: "canvas",
        troubleshootTip: { ko: "이런 개별 변경을 'Override'라고 불러요. 마스터 구조는 유지하면서 내용만 다르게 할 수 있어요.", en: "These individual changes are called 'Overrides'. You can keep the master structure while having different content." },
      },
      {
        id: 10,
        type: "action",
        instruction: { ko: "축하해요! 컴포넌트의 기본을 배웠어요. 마스터와 인스턴스 관계를 기억하세요.", en: "Congrats! You've learned component basics. Remember the master-instance relationship." },
        buttonText: { ko: "이해했어요!", en: "Got it!" },
        imageAlt: { ko: "컴포넌트 완료", en: "Component complete" },
        targetZone: "none",
        troubleshootTip: { ko: "컴포넌트를 사용하면 대규모 프로젝트에서 수백 개의 요소를 한 번에 수정할 수 있어요!", en: "With components, you can modify hundreds of elements at once in large projects!" },
      },
    ],
  },
  {
    day: 9,
    title: { ko: "프로토타이핑", en: "Prototyping" },
    subtitle: { ko: "인터랙션을 추가해서 디자인을 살려보세요", en: "Add interactions to bring your design to life" },
    steps: [
      {
        id: 1,
        type: "action",
        instruction: { ko: "새 프레임 2개를 만드세요 (Frame 1, Frame 2).", en: "Create 2 new frames (Frame 1, Frame 2)." },
        buttonText: { ko: "프레임 2개 생성!", en: "2 frames created!" },
        imageAlt: { ko: "프레임 2개", en: "2 frames" },
        targetZone: "canvas",
        shortcutKey: "F",
        troubleshootTip: { ko: "F를 눌러 프레임을 만드세요. 두 번째 프레임은 첫 번째 프레임 옆에 만드세요.", en: "Press F to create frames. Make the second frame next to the first one." },
      },
      {
        id: 2,
        type: "action",
        instruction: { ko: "Frame 1을 빨간색으로, Frame 2를 파란색으로 채우세요.", en: "Fill Frame 1 with red and Frame 2 with blue." },
        buttonText: { ko: "색상 적용!", en: "Colors applied!" },
        imageAlt: { ko: "빨강 파랑 프레임", en: "Red and blue frames" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "각 프레임을 선택하고 Fill 색상을 변경하세요.", en: "Select each frame and change the Fill color." },
      },
      {
        id: 3,
        type: "action",
        instruction: { ko: "오른쪽 사이드바 상단에서 'Prototype' 탭을 클릭하세요 (Design 옆).", en: "Click the 'Prototype' tab at the top of the right sidebar (next to Design)." },
        buttonText: { ko: "Prototype 탭 클릭!", en: "Clicked Prototype tab!" },
        imageAlt: { ko: "Prototype 탭", en: "Prototype tab" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "오른쪽 패널 상단에 'Design'과 'Prototype' 탭이 있어요. Prototype을 클릭하세요.", en: "There are 'Design' and 'Prototype' tabs at the top of the right panel. Click Prototype." },
      },
      {
        id: 4,
        type: "quiz",
        question: { ko: "Prototype 탭으로 전환하면 프레임에 무엇이 보이나요?", en: "What do you see on frames when you switch to Prototype tab?" },
        options: [
          { ko: "색상 피커", en: "Color picker" },
          { ko: "파란색 원형 노드", en: "Blue circular node" },
          { ko: "텍스트 편집기", en: "Text editor" }
        ],
        correctIndex: 1,
        successMessage: { ko: "맞아요! 파란색 노드는 인터랙션 연결점이에요. 드래그해서 다른 프레임으로 연결할 수 있어요.", en: "Right! The blue node is an interaction connection point. Drag it to connect to another frame." },
        imageAlt: { ko: "파란 노드", en: "Blue node" },
        targetZone: "canvas",
        troubleshootTip: { ko: "프레임을 선택하면 오른쪽에 파란색 원형 노드가 나타나요.", en: "When you select a frame, a blue circular node appears on the right." },
      },
      {
        id: 5,
        type: "action",
        instruction: { ko: "Frame 1의 파란 노드를 Frame 2로 드래그하세요.", en: "Drag Frame 1's blue node to Frame 2." },
        buttonText: { ko: "연결 완료!", en: "Connected!" },
        imageAlt: { ko: "프레임 연결", en: "Connecting frames" },
        targetZone: "canvas",
        troubleshootTip: { ko: "Frame 1을 선택하고, 오른쪽에 나타나는 파란 노드를 클릭한 채로 Frame 2까지 드래그하세요.", en: "Select Frame 1, then click and hold the blue node that appears on the right and drag to Frame 2." },
      },
      {
        id: 6,
        type: "action",
        instruction: { ko: "나타나는 메뉴에서 Trigger를 'On Click'으로 설정하세요.", en: "Set Trigger to 'On Click' in the menu that appears." },
        buttonText: { ko: "On Click 설정!", en: "On Click set!" },
        imageAlt: { ko: "Trigger 설정", en: "Setting Trigger" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "연결하면 오른쪽 패널에 Interaction 설정이 나타나요. Trigger 드롭다운에서 'On Click'을 선택하세요.", en: "After connecting, Interaction settings appear in the right panel. Select 'On Click' from the Trigger dropdown." },
      },
      {
        id: 7,
        type: "action",
        instruction: { ko: "Animation을 'Smart Animate'로 설정하세요.", en: "Set Animation to 'Smart Animate'." },
        buttonText: { ko: "Smart Animate 설정!", en: "Smart Animate set!" },
        imageAlt: { ko: "Animation 설정", en: "Setting Animation" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "Animation 드롭다운에서 'Smart Animate'를 선택하세요. 이 옵션은 부드러운 전환 효과를 만들어요.", en: "Select 'Smart Animate' from the Animation dropdown. This option creates smooth transition effects." },
      },
      {
        id: 8,
        type: "action",
        instruction: { ko: "오른쪽 상단의 재생 버튼(▶)을 클릭하세요.", en: "Click the play button (▶) in the top right." },
        buttonText: { ko: "재생 버튼 클릭!", en: "Play button clicked!" },
        imageAlt: { ko: "재생 버튼", en: "Play button" },
        targetZone: "toolbar-top",
        troubleshootTip: { ko: "상단 오른쪽에 있는 삼각형 재생 아이콘을 클릭하세요. 새 창이 열려요.", en: "Click the triangle play icon in the top right. A new window will open." },
      },
      {
        id: 9,
        type: "action",
        instruction: { ko: "새 창에서 빨간 프레임(Frame 1)을 클릭하세요.", en: "Click the red frame (Frame 1) in the new window." },
        buttonText: { ko: "클릭했어요!", en: "Clicked!" },
        imageAlt: { ko: "프로토타입 실행", en: "Running prototype" },
        targetZone: "none",
        troubleshootTip: { ko: "프로토타입 미리보기 창에서 빨간 화면을 클릭하면 파란 화면으로 전환돼요.", en: "Click the red screen in the prototype preview window to transition to the blue screen." },
      },
      {
        id: 10,
        type: "quiz",
        question: { ko: "빨간 프레임을 클릭하면 무슨 일이 일어나나요?", en: "What happens when you click the red frame?" },
        options: [
          { ko: "아무 일도 없다", en: "Nothing happens" },
          { ko: "파란 프레임으로 애니메이션 전환된다", en: "Animates to the blue frame" },
          { ko: "프레임이 삭제된다", en: "Frame gets deleted" }
        ],
        correctIndex: 1,
        successMessage: { ko: "축하해요! 첫 번째 인터랙티브 프로토타입을 만들었어요! 🎉", en: "Congrats! You've made your first interactive prototype! 🎉" },
        imageAlt: { ko: "애니메이션 전환", en: "Animation transition" },
        targetZone: "none",
        troubleshootTip: { ko: "Smart Animate 덕분에 부드럽게 전환돼요. 실제 앱처럼 동작하는 프로토타입을 만들 수 있어요!", en: "Thanks to Smart Animate, the transition is smooth. You can create prototypes that work like real apps!" },
      },
    ],
  },
  {
    day: 10,
    title: { ko: "내보내기 & 공유", en: "Export & Share" },
    subtitle: { ko: "완성된 디자인을 세상에 공유하세요", en: "Share your finished design with the world" },
    steps: [
      {
        id: 1,
        type: "action",
        instruction: { ko: "오른쪽 상단에서 'Design' 탭으로 돌아가세요.", en: "Go back to the 'Design' tab in the top right." },
        buttonText: { ko: "Design 탭!", en: "Design tab!" },
        imageAlt: { ko: "Design 탭", en: "Design tab" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "'Prototype' 탭 옆의 'Design' 탭을 클릭하세요.", en: "Click the 'Design' tab next to 'Prototype' tab." },
      },
      {
        id: 2,
        type: "action",
        instruction: { ko: "저장하고 싶은 프레임을 선택하세요.", en: "Select the frame you want to save." },
        buttonText: { ko: "프레임 선택!", en: "Frame selected!" },
        imageAlt: { ko: "프레임 선택", en: "Selecting frame" },
        targetZone: "canvas",
        troubleshootTip: { ko: "왼쪽 레이어 패널에서 프레임을 클릭하거나, 캔버스에서 직접 프레임을 클릭하세요.", en: "Click the frame in the left Layers panel or directly on the canvas." },
      },
      {
        id: 3,
        type: "action",
        instruction: { ko: "오른쪽 패널 맨 아래로 스크롤 → 'Export' 섹션을 찾으세요.", en: "Scroll to the bottom of the right panel → Find 'Export' section." },
        buttonText: { ko: "Export 찾음!", en: "Found Export!" },
        imageAlt: { ko: "Export 섹션", en: "Export section" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "오른쪽 패널을 맨 아래까지 스크롤하세요. 'Export' 섹션이 있어요.", en: "Scroll all the way down the right panel. You'll find the 'Export' section." },
      },
      {
        id: 4,
        type: "action",
        instruction: { ko: "Export 섹션의 '+' 버튼을 클릭하세요.", en: "Click the '+' button in the Export section." },
        buttonText: { ko: "+ 클릭!", en: "Clicked +!" },
        imageAlt: { ko: "Export + 버튼", en: "Export + button" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "'Export' 라벨 옆의 + 버튼을 클릭하면 내보내기 옵션이 추가돼요.", en: "Click the + button next to 'Export' label to add export options." },
      },
      {
        id: 5,
        type: "quiz",
        question: { ko: "이미지 내보내기에 가장 많이 쓰이는 형식은?", en: "What's the most commonly used format for image export?" },
        options: [
          { ko: "PDF", en: "PDF" },
          { ko: "PNG 또는 JPG", en: "PNG or JPG" },
          { ko: "SVG", en: "SVG" }
        ],
        correctIndex: 1,
        successMessage: { ko: "맞아요! PNG는 투명 배경을, JPG는 작은 파일 크기를 원할 때 사용해요.", en: "Right! Use PNG for transparent backgrounds, JPG for smaller file sizes." },
        imageAlt: { ko: "PNG/JPG", en: "PNG/JPG" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "PNG는 품질이 좋고 투명도를 지원해요. JPG는 사진에 적합하고 파일 크기가 작아요.", en: "PNG has good quality and supports transparency. JPG is good for photos and has smaller file size." },
      },
      {
        id: 6,
        type: "action",
        instruction: { ko: "PNG 또는 JPG를 선택하세요.", en: "Select PNG or JPG." },
        buttonText: { ko: "형식 선택!", en: "Format selected!" },
        imageAlt: { ko: "형식 선택", en: "Selecting format" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "드롭다운 메뉴에서 PNG 또는 JPG를 선택하세요. 2x, 3x로 고해상도 내보내기도 가능해요.", en: "Select PNG or JPG from the dropdown menu. You can also export at 2x, 3x for high resolution." },
      },
      {
        id: 7,
        type: "action",
        instruction: { ko: "'Export [프레임 이름]' 버튼을 클릭하세요. 파일이 컴퓨터에 저장됩니다!", en: "Click 'Export [frame name]' button. The file will be saved to your computer!" },
        buttonText: { ko: "내보내기 완료!", en: "Exported!" },
        imageAlt: { ko: "Export 버튼", en: "Export button" },
        targetZone: "sidebar-right",
        troubleshootTip: { ko: "버튼을 클릭하면 다운로드 폴더에 이미지가 저장돼요.", en: "Clicking the button saves the image to your downloads folder." },
      },
      {
        id: 8,
        type: "action",
        instruction: { ko: "오른쪽 상단의 파란색 'Share' 버튼을 클릭하세요.", en: "Click the blue 'Share' button in the top right." },
        buttonText: { ko: "Share 클릭!", en: "Clicked Share!" },
        imageAlt: { ko: "Share 버튼", en: "Share button" },
        targetZone: "toolbar-top",
        troubleshootTip: { ko: "화면 오른쪽 상단에 있는 파란색 'Share' 버튼을 찾으세요.", en: "Find the blue 'Share' button in the top right of the screen." },
      },
      {
        id: 9,
        type: "action",
        instruction: { ko: "'Copy link'를 클릭하세요.", en: "Click 'Copy link'." },
        buttonText: { ko: "링크 복사!", en: "Link copied!" },
        imageAlt: { ko: "Copy link", en: "Copy link" },
        targetZone: "none",
        troubleshootTip: { ko: "Share 메뉴에서 'Copy link' 버튼을 클릭하면 클립보드에 링크가 복사돼요.", en: "Click 'Copy link' in the Share menu to copy the link to your clipboard." },
      },
      {
        id: 10,
        type: "action",
        instruction: { ko: "축하합니다! 🎉 이 링크를 친구나 멘토에게 보내세요. 당신은 이제 Figma 사용자입니다!", en: "Congratulations! 🎉 Share this link with friends or mentors. You're now a Figma user!" },
        buttonText: { ko: "10일 챌린지 완료! 🎊", en: "10-Day Challenge Complete! 🎊" },
        imageAlt: { ko: "챌린지 완료", en: "Challenge complete" },
        targetZone: "none",
        troubleshootTip: { ko: "링크를 받은 사람은 Figma 계정이 없어도 디자인을 볼 수 있어요. 편집 권한도 설정할 수 있어요!", en: "Recipients can view the design without a Figma account. You can also set editing permissions!" },
      },
    ],
  },
];
