import { type TargetZone } from "@/components/FigmaUILocator";

export type StepType = "action" | "quiz";

export interface BaseStep {
  id: number;
  imageAlt: string;
  targetZone?: TargetZone;
  shortcutKey?: string;
  troubleshootTip?: string;
}

export interface ActionStep extends BaseStep {
  type: "action";
  instruction: string;
  buttonText: string;
}

export interface QuizStep extends BaseStep {
  type: "quiz";
  question: string;
  options: string[];
  correctIndex: number;
  successMessage: string;
}

export type MissionStep = ActionStep | QuizStep;

export interface DayMission {
  day: number;
  title: string;
  subtitle: string;
  steps: MissionStep[];
}

export const missionContent: DayMission[] = [
  {
    day: 1,
    title: "첫 번째 접촉",
    subtitle: "Figma 세계에 오신 것을 환영합니다",
    steps: [
      {
        id: 1,
        type: "action",
        instruction: "figma.com에 접속하고 로그인하세요.",
        buttonText: "로그인 완료!",
        imageAlt: "Figma 로그인 화면",
        targetZone: "none",
        troubleshootTip: "Google 계정이나 이메일로 회원가입할 수 있어요. 이미 계정이 있다면 로그인하세요.",
      },
      {
        id: 2,
        type: "action",
        instruction: "오른쪽 상단의 'Design File' (파란 버튼)을 클릭하세요.",
        buttonText: "파일 생성 완료!",
        imageAlt: "Design File 버튼 위치",
        targetZone: "toolbar-top",
        troubleshootTip: "파란색 '+ Design file' 버튼이 보이지 않으면, 홈 화면으로 이동해보세요. 왼쪽 상단의 Figma 로고를 클릭하면 됩니다.",
      },
      {
        id: 3,
        type: "quiz",
        question: "화면을 보세요. 무한 캔버스의 배경색은 무슨 색인가요?",
        options: ["흰색", "연한 회색", "검은색"],
        correctIndex: 1,
        successMessage: "정답! 연한 회색이 Figma의 기본 캔버스 색상이에요.",
        imageAlt: "Figma 캔버스 배경",
        targetZone: "canvas",
        troubleshootTip: "캔버스는 화면 중앙의 넓은 영역이에요. 프레임이나 도형이 아닌 배경 자체를 보세요.",
      },
      {
        id: 4,
        type: "action",
        instruction: "첫 번째 단축키를 외워볼까요? 키보드에서 'F'를 누르세요.",
        buttonText: "'F' 눌렀어요!",
        imageAlt: "키보드 F 키",
        targetZone: "toolbar-top",
        shortcutKey: "F",
        troubleshootTip: "텍스트 편집 모드에서는 단축키가 작동하지 않아요. 캔버스의 빈 공간을 한 번 클릭한 후 F를 눌러보세요.",
      },
      {
        id: 5,
        type: "quiz",
        question: "마우스 커서가 어떻게 변했나요?",
        options: ["사라졌다", "십자가(+) 모양으로 변했다", "손 모양으로 변했다"],
        correctIndex: 1,
        successMessage: "맞아요! 십자가 커서는 '그리기 모드'라는 뜻이에요.",
        imageAlt: "십자가 커서",
        targetZone: "canvas",
        troubleshootTip: "커서 변화가 안 보이면 F를 다시 눌러보세요. 상단 툴바에서 Frame 도구가 선택되어 있는지 확인하세요.",
      },
      {
        id: 6,
        type: "action",
        instruction: "좋아요! 이제 아무 곳이나 클릭하고 드래그해서 흰색 박스(프레임)를 그리세요.",
        buttonText: "프레임 완성!",
        imageAlt: "프레임 그리기",
        targetZone: "canvas",
        troubleshootTip: "클릭한 채로 드래그해야 해요. 클릭만 하면 프레임 옵션 패널이 나타납니다. 드래그하면서 원하는 크기로 그리세요.",
      },
      {
        id: 7,
        type: "action",
        instruction: "왼쪽 패널(레이어)을 보세요. 'Frame 1'이 보이나요?",
        buttonText: "보여요!",
        imageAlt: "레이어 패널에 Frame 1",
        targetZone: "sidebar-left",
        troubleshootTip: "왼쪽 패널이 안 보이면 View > Panels > Layers를 클릭하거나, 왼쪽 가장자리를 드래그해서 패널을 열어보세요.",
      },
      {
        id: 8,
        type: "action",
        instruction: "'R'을 눌러 사각형 도구를 선택하고, 프레임 '안에' 박스를 그리세요.",
        buttonText: "사각형 완성!",
        imageAlt: "사각형 그리기",
        targetZone: "canvas",
        shortcutKey: "R",
        troubleshootTip: "반드시 흰색 프레임 '안에' 그려야 해요. 프레임 밖에 그리면 레이어 패널에서 Frame 1의 자식으로 표시되지 않습니다.",
      },
      {
        id: 9,
        type: "quiz",
        question: "사각형의 색상을 바꾸려면 어느 패널을 사용해야 할까요?",
        options: ["왼쪽 패널", "오른쪽 패널", "상단 바"],
        correctIndex: 1,
        successMessage: "정답! 오른쪽 패널에서 디자인 속성을 수정할 수 있어요.",
        imageAlt: "오른쪽 디자인 패널",
        targetZone: "sidebar-right",
        troubleshootTip: "오른쪽 패널이 안 보이면 사각형을 선택한 상태인지 확인하세요. 선택된 요소가 있어야 속성 패널이 표시됩니다.",
      },
      {
        id: 10,
        type: "action",
        instruction: "오른쪽 패널에서 'Fill' 색상 사각형을 클릭하고 빨간색을 선택하세요.",
        buttonText: "색상 변경 완료!",
        imageAlt: "Fill 색상 변경",
        targetZone: "sidebar-right",
        troubleshootTip: "Fill 섹션에서 색상 사각형을 클릭하면 컬러 피커가 열려요. 빨간색 영역으로 드래그하거나 Hex 값에 FF0000을 입력하세요.",
      },
    ],
  },
  {
    day: 2,
    title: "인터페이스 탐험",
    subtitle: "Figma의 핵심 도구들을 마스터하세요",
    steps: [
      {
        id: 1,
        type: "action",
        instruction: "키보드에서 'F'를 누르세요 (프레임 도구).",
        buttonText: "'F' 눌렀어요!",
        imageAlt: "F 키 - 프레임 도구",
        targetZone: "toolbar-top",
        shortcutKey: "F",
        troubleshootTip: "캔버스 영역을 먼저 클릭해서 Figma에 포커스를 주세요. 다른 프로그램이 활성화되어 있으면 단축키가 작동하지 않아요.",
      },
      {
        id: 2,
        type: "action",
        instruction: "오른쪽 패널에서 'iPhone 14'를 선택하세요.",
        buttonText: "iPhone 14 선택 완료!",
        imageAlt: "iPhone 14 프리셋",
        targetZone: "sidebar-right",
        troubleshootTip: "Frame 도구가 선택된 상태에서 오른쪽 패널 상단의 'Phone' 섹션을 찾으세요. iPhone 14가 목록에 있어요.",
      },
      {
        id: 3,
        type: "quiz",
        question: "방금 만든 흰색 화면을 뭐라고 부를까요?",
        options: ["레이어", "프레임", "캔버스"],
        correctIndex: 1,
        successMessage: "정답! 프레임은 Figma에서 화면이나 컨테이너를 의미해요.",
        imageAlt: "프레임 설명",
        targetZone: "canvas",
        troubleshootTip: "프레임은 Figma의 기본 단위예요. 웹 디자인의 div나 앱 디자인의 화면과 비슷한 개념입니다.",
      },
      {
        id: 4,
        type: "action",
        instruction: "'R'을 누르세요 (사각형 도구).",
        buttonText: "'R' 눌렀어요!",
        imageAlt: "R 키 - 사각형 도구",
        targetZone: "toolbar-top",
        shortcutKey: "R",
        troubleshootTip: "R을 누르면 상단 툴바의 도형 메뉴에서 Rectangle이 선택됩니다. 커서가 십자가 모양으로 바뀌는지 확인하세요.",
      },
      {
        id: 5,
        type: "action",
        instruction: "프레임 안에 상자를 그리세요.",
        buttonText: "상자 완성!",
        imageAlt: "사각형 그리기",
        targetZone: "canvas",
        troubleshootTip: "iPhone 14 프레임 경계 안에서 드래그하세요. 왼쪽 레이어 패널에서 Rectangle이 Frame의 하위 요소로 표시되는지 확인하세요.",
      },
      {
        id: 6,
        type: "action",
        instruction: "'스페이스바'를 누른 채로 마우스를 드래그하세요 (Pan 이동).",
        buttonText: "캔버스 이동 완료!",
        imageAlt: "Pan 이동",
        targetZone: "canvas",
        shortcutKey: "Space",
        troubleshootTip: "스페이스바를 누르고 있는 동안 커서가 손 모양으로 바뀌어야 해요. 그 상태에서 마우스를 드래그하면 캔버스가 이동합니다.",
      },
      {
        id: 7,
        type: "quiz",
        question: "확대/축소하려면 어떤 키를 누른 채로 스크롤해야 할까요?",
        options: ["Shift", "Ctrl (또는 Cmd)", "Alt"],
        correctIndex: 1,
        successMessage: "맞아요! Ctrl/Cmd + 스크롤로 확대/축소할 수 있어요.",
        imageAlt: "확대/축소 설명",
        targetZone: "canvas",
        shortcutKey: "Ctrl",
        troubleshootTip: "Mac에서는 Cmd, Windows에서는 Ctrl을 사용하세요. 트랙패드라면 핀치 제스처로도 확대/축소할 수 있어요.",
      },
      {
        id: 8,
        type: "action",
        instruction: "'이동 도구' (화살표 아이콘)를 클릭하거나 'V'를 눌러 선택 모드로 전환하세요.",
        buttonText: "이동 도구 선택!",
        imageAlt: "이동 도구",
        targetZone: "toolbar-top",
        shortcutKey: "V",
        troubleshootTip: "V를 누르거나 상단 툴바 가장 왼쪽의 화살표 아이콘을 클릭하세요. 이 도구로 요소를 선택하고 이동할 수 있어요.",
      },
      {
        id: 9,
        type: "action",
        instruction: "사각형을 클릭하고 이리저리 움직여보세요.",
        buttonText: "이동 완료!",
        imageAlt: "사각형 이동",
        targetZone: "canvas",
        troubleshootTip: "사각형을 클릭해서 선택한 후 드래그하세요. 화살표 키로도 1px씩 이동할 수 있어요 (Shift+화살표는 10px).",
      },
      {
        id: 10,
        type: "action",
        instruction: "Ctrl/Cmd + 스크롤로 사각형을 확대해서 자세히 살펴보세요.",
        buttonText: "확대 완료!",
        imageAlt: "확대 연습",
        targetZone: "canvas",
        shortcutKey: "Ctrl",
        troubleshootTip: "마우스 커서가 있는 위치를 중심으로 확대됩니다. 사각형 위에 커서를 두고 스크롤하면 사각형이 커지는 것처럼 보여요.",
      },
    ],
  },
  {
    day: 3,
    title: "도형 마스터",
    subtitle: "다양한 도형과 라운딩을 배워보세요",
    steps: [
      {
        id: 1,
        type: "action",
        instruction: "새 프레임을 만드세요 (F 누르기).",
        buttonText: "프레임 생성!",
        imageAlt: "새 프레임 생성",
        targetZone: "canvas",
        shortcutKey: "F",
        troubleshootTip: "F를 누르고 캔버스의 빈 공간에서 드래그하세요. 기존 프레임 밖에 새 프레임을 만들어야 해요.",
      },
      {
        id: 2,
        type: "action",
        instruction: "사각형을 그리세요 (R 누르기).",
        buttonText: "사각형 완성!",
        imageAlt: "사각형 그리기",
        targetZone: "canvas",
        shortcutKey: "R",
        troubleshootTip: "R을 누르고 새로 만든 프레임 안에서 드래그하세요.",
      },
      {
        id: 3,
        type: "action",
        instruction: "사각형을 선택하고 오른쪽 패널의 'Corner radius' 섹션을 확인하세요.",
        buttonText: "확인했어요!",
        imageAlt: "Corner radius 섹션",
        targetZone: "sidebar-right",
        troubleshootTip: "사각형을 클릭해서 선택한 상태에서 오른쪽 패널을 스크롤하세요. 'Corner radius' 또는 모서리 아이콘을 찾으세요.",
      },
      {
        id: 4,
        type: "quiz",
        question: "'Corner Radius' 아이콘은 어떻게 생겼나요?",
        options: ["직선 모서리", "둥근 모서리 모양", "원형"],
        correctIndex: 1,
        successMessage: "맞아요! 둥근 모서리 아이콘이 Corner Radius예요.",
        imageAlt: "Corner Radius 아이콘",
        targetZone: "sidebar-right",
        troubleshootTip: "오른쪽 패널에서 작은 둥근 모서리 아이콘을 찾으세요. 숫자 입력 필드 옆에 있어요.",
      },
      {
        id: 5,
        type: "action",
        instruction: "반지름 박스에 '20'을 입력하세요. 모서리가 둥글어지는 걸 확인하세요!",
        buttonText: "라운딩 적용!",
        imageAlt: "라운딩 적용",
        targetZone: "sidebar-right",
        troubleshootTip: "숫자를 입력한 후 Enter를 눌러야 적용됩니다. 모서리가 안 둥글어지면 사각형이 선택되어 있는지 확인하세요.",
      },
      {
        id: 6,
        type: "action",
        instruction: "'O'를 누르세요 (원/타원 도구).",
        buttonText: "'O' 눌렀어요!",
        imageAlt: "O 키 - 원 도구",
        targetZone: "toolbar-top",
        shortcutKey: "O",
        troubleshootTip: "O를 누르면 상단 툴바에서 Ellipse 도구가 선택됩니다.",
      },
      {
        id: 7,
        type: "quiz",
        question: "완벽한 정원을 그리려면 어떤 키를 누른 채로 그려야 할까요?",
        options: ["Ctrl", "Alt", "Shift"],
        correctIndex: 2,
        successMessage: "정답! Shift를 누르면 비율이 고정돼요.",
        imageAlt: "Shift 키",
        targetZone: "canvas",
        shortcutKey: "Shift",
        troubleshootTip: "Shift 키는 비율을 1:1로 고정해요. 사각형을 그릴 때도 Shift를 누르면 정사각형이 됩니다.",
      },
      {
        id: 8,
        type: "action",
        instruction: "'Shift'를 누른 채로 그려서 완벽한 원을 만드세요.",
        buttonText: "정원 완성!",
        imageAlt: "정원 그리기",
        targetZone: "canvas",
        shortcutKey: "Shift",
        troubleshootTip: "Shift를 먼저 누르고, 누른 상태로 드래그하세요. 드래그 중간에 Shift를 누르면 안 돼요.",
      },
      {
        id: 9,
        type: "action",
        instruction: "원을 사각형 위에 배치하세요.",
        buttonText: "배치 완료!",
        imageAlt: "원 배치",
        targetZone: "canvas",
        troubleshootTip: "V를 눌러 선택 도구로 전환한 후 원을 드래그해서 사각형 위로 옮기세요.",
      },
      {
        id: 10,
        type: "action",
        instruction: "두 도형을 모두 선택하고 모서리를 드래그하여 크기를 조절해보세요.",
        buttonText: "크기 조절 완료!",
        imageAlt: "크기 조절",
        targetZone: "canvas",
        shortcutKey: "Shift",
        troubleshootTip: "여러 요소를 선택하려면 Shift를 누른 채로 클릭하거나, 드래그해서 여러 요소를 감싸세요.",
      },
    ],
  },
  {
    day: 4,
    title: "타이포그래피 마법",
    subtitle: "텍스트의 세계를 탐험하세요",
    steps: [
      {
        id: 1,
        type: "action",
        instruction: "'T'를 누르세요 (텍스트 도구).",
        buttonText: "'T' 눌렀어요!",
        imageAlt: "T 키 - 텍스트 도구",
        targetZone: "toolbar-top",
        shortcutKey: "T",
        troubleshootTip: "T를 누르면 커서가 텍스트 입력 모양으로 바뀌어요. 상단 툴바에서 T 아이콘이 선택되어 있는지 확인하세요.",
      },
      {
        id: 2,
        type: "action",
        instruction: "아무 곳이나 클릭하고 'Hello Figma'를 입력하세요.",
        buttonText: "텍스트 입력!",
        imageAlt: "텍스트 입력",
        targetZone: "canvas",
        troubleshootTip: "클릭하면 텍스트 입력 모드가 됩니다. 바로 타이핑을 시작하세요. 클릭 대신 드래그하면 텍스트 박스 너비가 고정돼요.",
      },
      {
        id: 3,
        type: "action",
        instruction: "텍스트를 드래그하여 전체 선택하세요.",
        buttonText: "선택 완료!",
        imageAlt: "텍스트 선택",
        targetZone: "canvas",
        shortcutKey: "Ctrl + A",
        troubleshootTip: "텍스트를 더블클릭해서 편집 모드로 들어간 후 Ctrl/Cmd + A를 누르면 전체 선택됩니다.",
      },
      {
        id: 4,
        type: "quiz",
        question: "텍스트 속성을 수정하려면 어느 패널의 어느 섹션을 봐야 할까요?",
        options: ["왼쪽 패널 - Layers", "오른쪽 패널 - Text", "상단 바 - Tools"],
        correctIndex: 1,
        successMessage: "맞아요! 오른쪽 패널의 Text 섹션에서 모든 텍스트 속성을 수정해요.",
        imageAlt: "Text 섹션",
        targetZone: "sidebar-right",
        troubleshootTip: "텍스트를 선택하면 오른쪽 패널에 'Text' 섹션이 나타나요. 폰트, 크기, 정렬 등을 변경할 수 있어요.",
      },
      {
        id: 5,
        type: "action",
        instruction: "폰트를 'Inter'에서 'Roboto' (또는 다른 폰트)로 변경하세요.",
        buttonText: "폰트 변경!",
        imageAlt: "폰트 변경",
        targetZone: "sidebar-right",
        troubleshootTip: "폰트 이름을 클릭하면 폰트 목록이 나타나요. 검색창에 원하는 폰트 이름을 입력해서 찾을 수 있어요.",
      },
      {
        id: 6,
        type: "action",
        instruction: "'Regular'를 'Bold'로 변경하세요.",
        buttonText: "굵기 변경!",
        imageAlt: "굵기 변경",
        targetZone: "sidebar-right",
        troubleshootTip: "폰트 이름 옆의 'Regular' 드롭다운을 클릭하세요. Bold, Medium, Light 등 다양한 옵션이 있어요.",
      },
      {
        id: 7,
        type: "action",
        instruction: "폰트 크기를 48로 변경하세요.",
        buttonText: "크기 변경!",
        imageAlt: "크기 변경",
        targetZone: "sidebar-right",
        troubleshootTip: "폰트 크기 숫자를 클릭하고 48을 입력한 후 Enter를 누르세요.",
      },
      {
        id: 8,
        type: "action",
        instruction: "색상 사각형(Fill)을 클릭하고 파란색을 선택하세요.",
        buttonText: "색상 변경!",
        imageAlt: "색상 변경",
        targetZone: "sidebar-right",
        troubleshootTip: "텍스트의 Fill 색상은 Text 섹션이 아닌 Fill 섹션에 있어요. 오른쪽 패널을 스크롤해서 찾으세요.",
      },
      {
        id: 9,
        type: "quiz",
        question: "텍스트를 가운데 정렬하려면 어디를 클릭해야 할까요?",
        options: ["왼쪽 정렬 아이콘", "가운데 정렬 아이콘", "Fill 색상"],
        correctIndex: 1,
        successMessage: "정답! 정렬 아이콘으로 텍스트 정렬을 바꿀 수 있어요.",
        imageAlt: "텍스트 정렬",
        targetZone: "sidebar-right",
        troubleshootTip: "Text 섹션에서 정렬 아이콘들을 찾으세요. 왼쪽, 가운데, 오른쪽, 양쪽 정렬 옵션이 있어요.",
      },
      {
        id: 10,
        type: "action",
        instruction: "정렬 아이콘을 사용하여 텍스트를 가운데 정렬하세요.",
        buttonText: "정렬 완료!",
        imageAlt: "가운데 정렬",
        targetZone: "sidebar-right",
        troubleshootTip: "가운데 정렬 아이콘은 가로선들이 가운데로 모인 모양이에요.",
      },
    ],
  },
  {
    day: 5,
    title: "색상 & 이미지",
    subtitle: "시각적 요소를 다루어보세요",
    steps: [
      {
        id: 1,
        type: "action",
        instruction: "사각형을 그리세요.",
        buttonText: "사각형 완성!",
        imageAlt: "사각형 그리기",
        targetZone: "canvas",
        shortcutKey: "R",
        troubleshootTip: "R을 눌러 사각형 도구를 선택하고 캔버스에서 드래그하세요.",
      },
      {
        id: 2,
        type: "action",
        instruction: "오른쪽 패널에서 'Fill' 색상 사각형을 클릭하세요.",
        buttonText: "Fill 클릭!",
        imageAlt: "Fill 클릭",
        targetZone: "sidebar-right",
        troubleshootTip: "사각형을 선택한 상태에서 오른쪽 패널의 Fill 섹션을 찾으세요. 색상 미리보기 사각형을 클릭하면 컬러 피커가 열려요.",
      },
      {
        id: 3,
        type: "action",
        instruction: "색상 피커를 빨간색으로 드래그해보세요.",
        buttonText: "빨간색 선택!",
        imageAlt: "빨간색 선택",
        targetZone: "sidebar-right",
        troubleshootTip: "컬러 피커에서 왼쪽의 색상 막대를 빨간색 영역으로 드래그하고, 중앙의 큰 영역에서 원하는 밝기/채도를 선택하세요.",
      },
      {
        id: 4,
        type: "quiz",
        question: "그라데이션(Gradient)을 적용하려면 'Solid' 대신 무엇을 선택해야 할까요?",
        options: ["Image", "Linear", "None"],
        correctIndex: 1,
        successMessage: "맞아요! Linear는 선형 그라데이션을 의미해요.",
        imageAlt: "그라데이션 설명",
        targetZone: "sidebar-right",
        troubleshootTip: "컬러 피커 상단에 'Solid'라고 적힌 드롭다운이 있어요. 클릭하면 Linear, Radial 등의 그라데이션 옵션이 나와요.",
      },
      {
        id: 5,
        type: "action",
        instruction: "색상 창 상단의 'Solid' → 'Linear' (그라데이션)으로 변경하세요.",
        buttonText: "그라데이션 적용!",
        imageAlt: "그라데이션 적용",
        targetZone: "sidebar-right",
        troubleshootTip: "Linear를 선택하면 캔버스의 사각형에 그라데이션 핸들이 나타나요. 드래그해서 방향을 바꿀 수 있어요.",
      },
      {
        id: 6,
        type: "action",
        instruction: "오른쪽 패널에서 'Stroke' (테두리)를 추가하세요.",
        buttonText: "Stroke 추가!",
        imageAlt: "Stroke 추가",
        targetZone: "sidebar-right",
        troubleshootTip: "Stroke 섹션 옆의 + 버튼을 클릭하세요. 없다면 Fill 아래쪽을 확인해보세요.",
      },
      {
        id: 7,
        type: "action",
        instruction: "Stroke 크기를 10으로 설정하세요.",
        buttonText: "크기 설정!",
        imageAlt: "Stroke 크기",
        targetZone: "sidebar-right",
        troubleshootTip: "Stroke 섹션에서 숫자를 클릭하고 10을 입력한 후 Enter를 누르세요.",
      },
      {
        id: 8,
        type: "action",
        instruction: "컴퓨터에서 이미지를 찾아 Figma 캔버스로 드래그 앤 드롭하세요.",
        buttonText: "이미지 추가!",
        imageAlt: "이미지 드래그",
        targetZone: "canvas",
        troubleshootTip: "파일 탐색기에서 이미지 파일을 Figma 창으로 직접 드래그하세요. PNG, JPG, SVG 등 다양한 형식을 지원해요.",
      },
      {
        id: 9,
        type: "quiz",
        question: "이미지 비율을 유지하면서 크기를 조절하려면 어떤 키를 눌러야 할까요?",
        options: ["Ctrl", "Alt", "Shift"],
        correctIndex: 2,
        successMessage: "정답! Shift를 누르면 비율이 고정돼요.",
        imageAlt: "Shift 키 설명",
        targetZone: "canvas",
        shortcutKey: "Shift",
        troubleshootTip: "Shift 없이 모서리를 드래그하면 이미지가 찌그러질 수 있어요. 항상 Shift를 누른 채로 크기를 조절하세요.",
      },
      {
        id: 10,
        type: "action",
        instruction: "Shift를 눌러 비율을 유지하면서 이미지 크기를 조절하세요.",
        buttonText: "크기 조절 완료!",
        imageAlt: "이미지 크기 조절",
        targetZone: "canvas",
        shortcutKey: "Shift",
        troubleshootTip: "이미지의 모서리 핸들을 Shift를 누른 채로 드래그하세요.",
      },
    ],
  },
  {
    day: 6,
    title: "그룹 & 정렬",
    subtitle: "요소들을 체계적으로 정리하세요",
    steps: [
      {
        id: 1,
        type: "action",
        instruction: "서로 다른 사각형 3개를 그리세요.",
        buttonText: "사각형 3개 완성!",
        imageAlt: "사각형 3개",
        targetZone: "canvas",
        shortcutKey: "R",
        troubleshootTip: "R을 눌러 사각형을 하나 그리고, 다시 R을 눌러 다른 위치에 사각형을 그리세요. 3번 반복하세요.",
      },
      {
        id: 2,
        type: "action",
        instruction: "모두 선택하세요 (드래그하여 선택).",
        buttonText: "모두 선택!",
        imageAlt: "모두 선택",
        targetZone: "canvas",
        troubleshootTip: "V를 눌러 선택 도구로 전환한 후, 세 사각형을 모두 포함하도록 드래그하세요.",
      },
      {
        id: 3,
        type: "quiz",
        question: "선택한 요소들을 그룹화하는 단축키는 무엇일까요?",
        options: ["Ctrl + G", "Ctrl + A", "Ctrl + C"],
        correctIndex: 0,
        successMessage: "맞아요! Ctrl(Cmd) + G로 그룹화할 수 있어요.",
        imageAlt: "그룹화 단축키",
        targetZone: "canvas",
        shortcutKey: "Ctrl + G",
        troubleshootTip: "Mac에서는 Cmd + G, Windows에서는 Ctrl + G를 사용하세요.",
      },
      {
        id: 4,
        type: "action",
        instruction: "'Ctrl + G' (또는 Cmd + G)를 눌러 그룹화하세요.",
        buttonText: "그룹화 완료!",
        imageAlt: "그룹화",
        targetZone: "canvas",
        shortcutKey: "Ctrl + G",
        troubleshootTip: "세 요소가 모두 선택된 상태에서 단축키를 누르세요. 왼쪽 레이어 패널에서 'Group'이 생성되는지 확인하세요.",
      },
      {
        id: 5,
        type: "action",
        instruction: "왼쪽 패널을 확인하세요 → 'Group 1'이 보입니다.",
        buttonText: "확인했어요!",
        imageAlt: "Group 1",
        targetZone: "sidebar-left",
        troubleshootTip: "레이어 패널에서 'Group' 레이어를 클릭하면 하위 요소들이 접히거나 펼쳐져요.",
      },
      {
        id: 6,
        type: "action",
        instruction: "그룹을 이동하세요. 함께 움직이는 것을 확인하세요!",
        buttonText: "그룹 이동!",
        imageAlt: "그룹 이동",
        targetZone: "canvas",
        troubleshootTip: "그룹을 선택하고 드래그하면 내부의 모든 요소가 함께 이동해요.",
      },
      {
        id: 7,
        type: "action",
        instruction: "그룹 해제하세요 (Ctrl + Shift + G).",
        buttonText: "그룹 해제!",
        imageAlt: "그룹 해제",
        targetZone: "canvas",
        shortcutKey: "Ctrl + Shift + G",
        troubleshootTip: "그룹이 선택된 상태에서 Ctrl(Cmd) + Shift + G를 누르세요.",
      },
      {
        id: 8,
        type: "action",
        instruction: "3개를 다시 모두 선택하세요.",
        buttonText: "다시 선택!",
        imageAlt: "다시 선택",
        targetZone: "canvas",
        troubleshootTip: "드래그해서 선택하거나 Shift를 누른 채로 하나씩 클릭하세요.",
      },
      {
        id: 9,
        type: "quiz",
        question: "요소들을 균등하게 정렬하려면 어떤 도구를 사용해야 할까요?",
        options: ["그룹화", "Tidy Up / 정렬 도구", "복제"],
        correctIndex: 1,
        successMessage: "맞아요! Tidy Up이나 정렬 도구로 요소들을 깔끔하게 배치할 수 있어요.",
        imageAlt: "정렬 도구",
        targetZone: "toolbar-top",
        troubleshootTip: "여러 요소를 선택하면 선택 영역 우하단에 Tidy Up 아이콘이 나타나요.",
      },
      {
        id: 10,
        type: "action",
        instruction: "정렬 도구를 사용하여 사각형들을 상단 정렬하세요.",
        buttonText: "상단 정렬 완료!",
        imageAlt: "상단 정렬",
        targetZone: "sidebar-right",
        troubleshootTip: "오른쪽 패널 상단의 정렬 아이콘들 중 'Align top' 아이콘을 클릭하세요.",
      },
    ],
  },
  {
    day: 7,
    title: "오토 레이아웃",
    subtitle: "자동으로 정렬되는 마법을 배워보세요",
    steps: [
      {
        id: 1,
        type: "action",
        instruction: "'T'를 누르고 'Button'이라고 입력하세요.",
        buttonText: "텍스트 입력!",
        imageAlt: "Button 텍스트",
        targetZone: "canvas",
        shortcutKey: "T",
        troubleshootTip: "T를 누르고 캔버스를 클릭한 후 'Button'을 입력하세요.",
      },
      {
        id: 2,
        type: "action",
        instruction: "텍스트를 선택하고 'Shift + A'를 누르세요 (오토 레이아웃 추가).",
        buttonText: "오토 레이아웃 적용!",
        imageAlt: "Shift + A",
        targetZone: "canvas",
        shortcutKey: "Shift + A",
        troubleshootTip: "텍스트를 선택한 상태에서 Shift + A를 누르세요. 텍스트 주위에 프레임이 생겨요.",
      },
      {
        id: 3,
        type: "quiz",
        question: "오토 레이아웃을 적용하면 무엇이 생기나요?",
        options: ["색상이 바뀐다", "텍스트 주위에 프레임이 생긴다", "텍스트가 사라진다"],
        correctIndex: 1,
        successMessage: "맞아요! 오토 레이아웃은 요소 주위에 스마트한 프레임을 만들어요.",
        imageAlt: "오토 레이아웃 프레임",
        targetZone: "sidebar-left",
        troubleshootTip: "왼쪽 레이어 패널을 보면 텍스트가 새 Frame 안에 들어간 것을 확인할 수 있어요.",
      },
      {
        id: 4,
        type: "action",
        instruction: "새로 생긴 프레임을 선택하고 Fill 색상을 추가하세요.",
        buttonText: "색상 추가!",
        imageAlt: "Fill 색상 추가",
        targetZone: "sidebar-right",
        troubleshootTip: "프레임을 선택하고 오른쪽 패널 Fill 섹션의 + 버튼을 클릭하세요.",
      },
      {
        id: 5,
        type: "action",
        instruction: "오른쪽 'Auto Layout' 패널에서 'Horizontal padding'을 24로 변경하세요.",
        buttonText: "패딩 변경!",
        imageAlt: "Horizontal padding",
        targetZone: "sidebar-right",
        troubleshootTip: "Auto Layout 섹션에서 좌우 패딩 값을 찾아 24를 입력하세요.",
      },
      {
        id: 6,
        type: "action",
        instruction: "'Vertical padding'을 12로 변경하세요.",
        buttonText: "수직 패딩 변경!",
        imageAlt: "Vertical padding",
        targetZone: "sidebar-right",
        troubleshootTip: "상하 패딩 값을 12로 변경하세요.",
      },
      {
        id: 7,
        type: "action",
        instruction: "Corner Radius를 8로 설정하세요. 버튼이 완성되었어요!",
        buttonText: "버튼 완성!",
        imageAlt: "버튼 완성",
        targetZone: "sidebar-right",
        troubleshootTip: "프레임의 Corner radius 값을 8로 변경하세요.",
      },
      {
        id: 8,
        type: "action",
        instruction: "텍스트를 더블클릭해서 'Click Me!'로 변경해보세요. 버튼이 자동으로 커지나요?",
        buttonText: "텍스트 변경!",
        imageAlt: "텍스트 변경",
        targetZone: "canvas",
        troubleshootTip: "오토 레이아웃 덕분에 텍스트 길이에 따라 버튼 크기가 자동 조절돼요. 이게 오토 레이아웃의 마법이에요!",
      },
      {
        id: 9,
        type: "action",
        instruction: "버튼을 복제하세요 (Alt + 드래그).",
        buttonText: "복제 완료!",
        imageAlt: "버튼 복제",
        targetZone: "canvas",
        shortcutKey: "Alt",
        troubleshootTip: "Alt(Option)를 누른 채로 버튼을 드래그하면 복제됩니다.",
      },
      {
        id: 10,
        type: "action",
        instruction: "두 버튼을 모두 선택하고 'Shift + A'를 다시 누르세요 (버튼 리스트 만들기).",
        buttonText: "버튼 리스트 완성!",
        imageAlt: "버튼 리스트",
        targetZone: "canvas",
        shortcutKey: "Shift + A",
        troubleshootTip: "두 버튼을 선택한 상태에서 Shift + A를 누르면 오토 레이아웃 리스트가 만들어져요.",
      },
    ],
  },
  {
    day: 8,
    title: "컴포넌트",
    subtitle: "재사용 가능한 디자인 요소를 만드세요",
    steps: [
      {
        id: 1,
        type: "action",
        instruction: "Day 7에서 만든 버튼을 선택하세요 (없다면 새로 만드세요).",
        buttonText: "버튼 선택!",
        imageAlt: "버튼 선택",
        targetZone: "canvas",
        troubleshootTip: "오토 레이아웃이 적용된 버튼이 필요해요. T로 텍스트를 만들고 Shift+A로 오토 레이아웃을 적용하세요.",
      },
      {
        id: 2,
        type: "action",
        instruction: "상단 가운데 툴바에서 다이아몬드 아이콘 (Create Component)을 클릭하세요.",
        buttonText: "컴포넌트 생성!",
        imageAlt: "Create Component",
        targetZone: "toolbar-top",
        shortcutKey: "Ctrl + Alt + K",
        troubleshootTip: "상단 툴바 중앙에 있는 다이아몬드 모양 아이콘을 찾으세요. 또는 Ctrl(Cmd) + Alt + K를 누르세요.",
      },
      {
        id: 3,
        type: "quiz",
        question: "컴포넌트로 만들면 테두리 색이 어떻게 변하나요?",
        options: ["파란색", "보라색", "초록색"],
        correctIndex: 1,
        successMessage: "맞아요! 보라색 테두리는 이것이 '마스터' 컴포넌트라는 표시예요.",
        imageAlt: "보라색 테두리",
        targetZone: "canvas",
        troubleshootTip: "컴포넌트가 되면 선택 시 보라색 테두리가 보여요. 왼쪽 레이어 패널에서도 다이아몬드 아이콘이 표시돼요.",
      },
      {
        id: 4,
        type: "action",
        instruction: "Alt를 누른 채로 컴포넌트를 드래그해서 복사본(인스턴스)을 만드세요.",
        buttonText: "인스턴스 생성!",
        imageAlt: "인스턴스 생성",
        targetZone: "canvas",
        shortcutKey: "Alt",
        troubleshootTip: "Alt(Option) + 드래그로 복제하면 인스턴스가 생겨요. 인스턴스는 빈 다이아몬드 아이콘으로 표시돼요.",
      },
      {
        id: 5,
        type: "action",
        instruction: "인스턴스를 2개 더 만들어서 총 3개의 인스턴스를 만드세요.",
        buttonText: "3개 인스턴스 완성!",
        imageAlt: "3개 인스턴스",
        targetZone: "canvas",
        troubleshootTip: "Alt + 드래그를 반복하거나, 복제 후 Ctrl(Cmd) + D로 같은 간격으로 추가 복제할 수 있어요.",
      },
      {
        id: 6,
        type: "action",
        instruction: "'마스터' 컴포넌트(보라색 채워진 다이아몬드)의 색상을 초록색으로 변경하세요.",
        buttonText: "색상 변경!",
        imageAlt: "마스터 색상 변경",
        targetZone: "sidebar-right",
        troubleshootTip: "마스터 컴포넌트를 선택하고 Fill 색상을 변경하세요.",
      },
      {
        id: 7,
        type: "quiz",
        question: "마스터 컴포넌트의 색상을 바꾸면 인스턴스들은 어떻게 되나요?",
        options: ["변하지 않는다", "모두 같이 바뀐다", "삭제된다"],
        correctIndex: 1,
        successMessage: "정답! 마스터를 수정하면 모든 인스턴스가 자동으로 업데이트돼요. 이게 컴포넌트의 힘이에요!",
        imageAlt: "인스턴스 업데이트",
        targetZone: "canvas",
        troubleshootTip: "모든 인스턴스가 초록색으로 바뀌었는지 확인하세요.",
      },
      {
        id: 8,
        type: "action",
        instruction: "인스턴스 하나의 텍스트를 'Log in'으로 변경하세요.",
        buttonText: "텍스트 변경!",
        imageAlt: "인스턴스 텍스트 변경",
        targetZone: "canvas",
        troubleshootTip: "인스턴스의 텍스트를 더블클릭해서 편집하세요. 텍스트는 개별적으로 변경할 수 있어요.",
      },
      {
        id: 9,
        type: "quiz",
        question: "인스턴스에서 개별적으로 바꿀 수 있는 것은?",
        options: ["아무것도 못 바꾼다", "텍스트, 색상 등 속성을 개별 변경 가능", "크기만 바꿀 수 있다"],
        correctIndex: 1,
        successMessage: "맞아요! 인스턴스는 마스터의 구조를 따르지만, 텍스트나 색상 같은 속성은 개별 수정할 수 있어요.",
        imageAlt: "인스턴스 오버라이드",
        targetZone: "canvas",
        troubleshootTip: "이런 개별 변경을 'Override'라고 불러요. 마스터 구조는 유지하면서 내용만 다르게 할 수 있어요.",
      },
      {
        id: 10,
        type: "action",
        instruction: "축하해요! 컴포넌트의 기본을 배웠어요. 마스터와 인스턴스 관계를 기억하세요.",
        buttonText: "이해했어요!",
        imageAlt: "컴포넌트 완료",
        targetZone: "none",
        troubleshootTip: "컴포넌트를 사용하면 대규모 프로젝트에서 수백 개의 요소를 한 번에 수정할 수 있어요!",
      },
    ],
  },
  {
    day: 9,
    title: "프로토타이핑",
    subtitle: "인터랙션을 추가해서 디자인을 살려보세요",
    steps: [
      {
        id: 1,
        type: "action",
        instruction: "새 프레임 2개를 만드세요 (Frame 1, Frame 2).",
        buttonText: "프레임 2개 생성!",
        imageAlt: "프레임 2개",
        targetZone: "canvas",
        shortcutKey: "F",
        troubleshootTip: "F를 눌러 프레임을 만드세요. 두 번째 프레임은 첫 번째 프레임 옆에 만드세요.",
      },
      {
        id: 2,
        type: "action",
        instruction: "Frame 1을 빨간색으로, Frame 2를 파란색으로 채우세요.",
        buttonText: "색상 적용!",
        imageAlt: "빨강 파랑 프레임",
        targetZone: "sidebar-right",
        troubleshootTip: "각 프레임을 선택하고 Fill 색상을 변경하세요.",
      },
      {
        id: 3,
        type: "action",
        instruction: "오른쪽 사이드바 상단에서 'Prototype' 탭을 클릭하세요 (Design 옆).",
        buttonText: "Prototype 탭 클릭!",
        imageAlt: "Prototype 탭",
        targetZone: "sidebar-right",
        troubleshootTip: "오른쪽 패널 상단에 'Design'과 'Prototype' 탭이 있어요. Prototype을 클릭하세요.",
      },
      {
        id: 4,
        type: "quiz",
        question: "Prototype 탭으로 전환하면 프레임에 무엇이 보이나요?",
        options: ["색상 피커", "파란색 원형 노드", "텍스트 편집기"],
        correctIndex: 1,
        successMessage: "맞아요! 파란색 노드는 인터랙션 연결점이에요. 드래그해서 다른 프레임으로 연결할 수 있어요.",
        imageAlt: "파란 노드",
        targetZone: "canvas",
        troubleshootTip: "프레임을 선택하면 오른쪽에 파란색 원형 노드가 나타나요.",
      },
      {
        id: 5,
        type: "action",
        instruction: "Frame 1의 파란 노드를 Frame 2로 드래그하세요.",
        buttonText: "연결 완료!",
        imageAlt: "프레임 연결",
        targetZone: "canvas",
        troubleshootTip: "Frame 1을 선택하고, 오른쪽에 나타나는 파란 노드를 클릭한 채로 Frame 2까지 드래그하세요.",
      },
      {
        id: 6,
        type: "action",
        instruction: "나타나는 메뉴에서 Trigger를 'On Click'으로 설정하세요.",
        buttonText: "On Click 설정!",
        imageAlt: "Trigger 설정",
        targetZone: "sidebar-right",
        troubleshootTip: "연결하면 오른쪽 패널에 Interaction 설정이 나타나요. Trigger 드롭다운에서 'On Click'을 선택하세요.",
      },
      {
        id: 7,
        type: "action",
        instruction: "Animation을 'Smart Animate'로 설정하세요.",
        buttonText: "Smart Animate 설정!",
        imageAlt: "Animation 설정",
        targetZone: "sidebar-right",
        troubleshootTip: "Animation 드롭다운에서 'Smart Animate'를 선택하세요. 이 옵션은 부드러운 전환 효과를 만들어요.",
      },
      {
        id: 8,
        type: "action",
        instruction: "오른쪽 상단의 재생 버튼(▶)을 클릭하세요.",
        buttonText: "재생 버튼 클릭!",
        imageAlt: "재생 버튼",
        targetZone: "toolbar-top",
        troubleshootTip: "상단 오른쪽에 있는 삼각형 재생 아이콘을 클릭하세요. 새 창이 열려요.",
      },
      {
        id: 9,
        type: "action",
        instruction: "새 창에서 빨간 프레임(Frame 1)을 클릭하세요.",
        buttonText: "클릭했어요!",
        imageAlt: "프로토타입 실행",
        targetZone: "none",
        troubleshootTip: "프로토타입 미리보기 창에서 빨간 화면을 클릭하면 파란 화면으로 전환돼요.",
      },
      {
        id: 10,
        type: "quiz",
        question: "빨간 프레임을 클릭하면 무슨 일이 일어나나요?",
        options: ["아무 일도 없다", "파란 프레임으로 애니메이션 전환된다", "프레임이 삭제된다"],
        correctIndex: 1,
        successMessage: "축하해요! 첫 번째 인터랙티브 프로토타입을 만들었어요! 🎉",
        imageAlt: "애니메이션 전환",
        targetZone: "none",
        troubleshootTip: "Smart Animate 덕분에 부드럽게 전환돼요. 실제 앱처럼 동작하는 프로토타입을 만들 수 있어요!",
      },
    ],
  },
  {
    day: 10,
    title: "내보내기 & 공유",
    subtitle: "완성된 디자인을 세상에 공유하세요",
    steps: [
      {
        id: 1,
        type: "action",
        instruction: "오른쪽 상단에서 'Design' 탭으로 돌아가세요.",
        buttonText: "Design 탭!",
        imageAlt: "Design 탭",
        targetZone: "sidebar-right",
        troubleshootTip: "'Prototype' 탭 옆의 'Design' 탭을 클릭하세요.",
      },
      {
        id: 2,
        type: "action",
        instruction: "저장하고 싶은 프레임을 선택하세요.",
        buttonText: "프레임 선택!",
        imageAlt: "프레임 선택",
        targetZone: "canvas",
        troubleshootTip: "왼쪽 레이어 패널에서 프레임을 클릭하거나, 캔버스에서 직접 프레임을 클릭하세요.",
      },
      {
        id: 3,
        type: "action",
        instruction: "오른쪽 패널 맨 아래로 스크롤 → 'Export' 섹션을 찾으세요.",
        buttonText: "Export 찾음!",
        imageAlt: "Export 섹션",
        targetZone: "sidebar-right",
        troubleshootTip: "오른쪽 패널을 맨 아래까지 스크롤하세요. 'Export' 섹션이 있어요.",
      },
      {
        id: 4,
        type: "action",
        instruction: "Export 섹션의 '+' 버튼을 클릭하세요.",
        buttonText: "+ 클릭!",
        imageAlt: "Export + 버튼",
        targetZone: "sidebar-right",
        troubleshootTip: "'Export' 라벨 옆의 + 버튼을 클릭하면 내보내기 옵션이 추가돼요.",
      },
      {
        id: 5,
        type: "quiz",
        question: "이미지 내보내기에 가장 많이 쓰이는 형식은?",
        options: ["PDF", "PNG 또는 JPG", "SVG"],
        correctIndex: 1,
        successMessage: "맞아요! PNG는 투명 배경을, JPG는 작은 파일 크기를 원할 때 사용해요.",
        imageAlt: "PNG/JPG",
        targetZone: "sidebar-right",
        troubleshootTip: "PNG는 품질이 좋고 투명도를 지원해요. JPG는 사진에 적합하고 파일 크기가 작아요.",
      },
      {
        id: 6,
        type: "action",
        instruction: "PNG 또는 JPG를 선택하세요.",
        buttonText: "형식 선택!",
        imageAlt: "형식 선택",
        targetZone: "sidebar-right",
        troubleshootTip: "드롭다운 메뉴에서 PNG 또는 JPG를 선택하세요. 2x, 3x로 고해상도 내보내기도 가능해요.",
      },
      {
        id: 7,
        type: "action",
        instruction: "'Export [프레임 이름]' 버튼을 클릭하세요. 파일이 컴퓨터에 저장됩니다!",
        buttonText: "내보내기 완료!",
        imageAlt: "Export 버튼",
        targetZone: "sidebar-right",
        troubleshootTip: "버튼을 클릭하면 다운로드 폴더에 이미지가 저장돼요.",
      },
      {
        id: 8,
        type: "action",
        instruction: "오른쪽 상단의 파란색 'Share' 버튼을 클릭하세요.",
        buttonText: "Share 클릭!",
        imageAlt: "Share 버튼",
        targetZone: "toolbar-top",
        troubleshootTip: "화면 오른쪽 상단에 있는 파란색 'Share' 버튼을 찾으세요.",
      },
      {
        id: 9,
        type: "action",
        instruction: "'Copy link'를 클릭하세요.",
        buttonText: "링크 복사!",
        imageAlt: "Copy link",
        targetZone: "none",
        troubleshootTip: "Share 메뉴에서 'Copy link' 버튼을 클릭하면 클립보드에 링크가 복사돼요.",
      },
      {
        id: 10,
        type: "action",
        instruction: "축하합니다! 🎉 이 링크를 친구나 멘토에게 보내세요. 당신은 이제 Figma 사용자입니다!",
        buttonText: "10일 챌린지 완료! 🎊",
        imageAlt: "챌린지 완료",
        targetZone: "none",
        troubleshootTip: "링크를 받은 사람은 Figma 계정이 없어도 디자인을 볼 수 있어요. 편집 권한도 설정할 수 있어요!",
      },
    ],
  },
];
